In Antarctica and the Artic, ice melts are causing complex questions about the impact of global warming.
In Antarctica huge glaciers are thinning and ice shelves are either disintegrating or retreating.
These findings are possible indications of global warming.
Information gathered about Antarctica coincides with a recent report on accelerating climate changes in the Arctic.
A Chinese scientist predicted that the Artic icecap would melt by 2080.
The Arctic's indigenous people (about 4 million) are fighting global warming because it will be a threat to their societies, economies and culture.
