Hundreds of animal welfare workers and volunteers from the gulf coast and across the nation are working to rescue pets stranded by Hurricane Katrina.
The Humane Society, SPCA and other organizations have joined the effort.
The ASPCA has received donations of over $5.25 million, and shipments of food and supplies.
Nearly 4,000 animals have been rescued, and 300-400 have been reunited with their owners.
Hundreds of animals arrive daily at the Lamar-Dixon Center in Gonzales, LA where about 2,000 are housed.
The animals are photographed, micro chipped and documented before being shipped to other shelters.
Pictures are posted on Petfinder.com.
