Hurricane Katrina evacuees were forced to abandon possibly 50,000 dogs, cats, birds and other pets.
Volunteers with the Humane Society, the ASPCA, other groups, and soldiers searched for pets trapped in houses and left food for animals roaming streets.
Rescued pets were taken to Gonzales, LA and Hattiesburg, MS.
4,000 pets had been rescued by 9/13/05 and a small fraction reunited with owners.
To ease overcrowding some dogs were relocated to other states after being photographed, microchipped and documented.
Pet photographs were posted on the website petfinder.com.
Federal, state and local assistance was requested.
The ASPCA received over $5.25 million.
