Christians constitute about three percent of Iraq's population of 25 million.
In August 2004 five churches in Baghdad and Mosul were blown up and in the following two months it is estimated that 15,000 Christians left for Syria and Jordan.
Many of the emigrants blamed the attacks not on Muslim Iraqis but on foreigners.
By January 2005 the Christian minority was organized into political parties in preparation for the January 30th parliamentary elections.
On January 15th gunmen kidnapped the Syrian Archbishop of Mosul, an act interpreted as warning Christians not to vote in the forthcoming elections.
