Accident and death rates continue to increase at China's provincial coal mines, while rates decrease at state-owned facilities.
In response, officials will close 4,000 small coal mines annually for three years and further reduce the number through regrouping and mergers.
Already, 2,411 mines were closed this year and 12,900 were ordered to suspend production for safety problems.
Fines have been established for wrongful deaths, and rewards offered to whistleblowers.
Advanced gas monitors were installed in 20-some gas-rich coal mines.
Two deputy governors were dismissed, 96 officials were prosecuted, and another 126 officials were demoted or fired for safety violations.
