The Jan.30, 2005 election produced only one seat for Christian Parties in the 275-seat Iraq National Assembly.
Christians protested irregularities which prevented many from voting.
Now the main concern was that minority rights be enshrined in the constitution to be written by the National Assembly.
On March 16, 2005 a Christian general in the Iraqi police force was shot dead by a group affiliated with Al-Qaeda.
In November in Baghdad gunmen killed four Christian women.
Emigration of Iraqi Christians continues with the number since the American takeover estimated from 20,000 to 200,000.
