Government officials have announced that 4,000 small coalmines will be closed by the end of 2005.
One city in north China has imposed huge fines on coalmines for each death in accidents.
In Hunan Province cash awards are offered to those who report officials who illegally own shares in mines.
In December 2005 the government announced that it had dismissed two provincial deputy governors, prosecuted 96 officials and demoted or dismissed 126 other officials blamed for accidents killing 528 people.
Despite such measures the rate of large-scale accidents increases with accidents reported on a near-daily basis.
