Retired FBI official Mark Felt revealed himself to be the Watergate informant Deep Throat in a Vanity Fair article, ending 33 years of speculation.
The revelation surprised everyone, particularly reporters Woodward and Bernstein, who vowed to keep his secret until after his death.
Political celebrities, pundits, and minor Watergate figures now claim to have known all along.
Felt is being hailed as a hero, denounced as a traitor and accused of partisan politics.
A number of other Deep Throat suspects are relieved to be exonerated.
Newspapers claim it is an example of how anonymous sources can keep government in check.
