Libby's lawyers have asked a federal judge to dismiss the indictment, claiming that the prosecutor lacked the legal authority to indict Libby.
The Special Counsel disputes that claim.
Libby's trial has been set for January 2007.
He is expected to testify that he was too involved with national security issues to recall minor events such as conversations with reporters.
A federal judge has ordered the government to provide Libby with redacted versions of various documents and other information he requested.
Meanwhile the special prosecutor is back at work before another grand jury with Rove still under investigation.
