Hurricane Katrina has left thousands of animals stranded in New Orleans.
Many pet owners were forced to abandon their animals in the evacuation of the city, although some owners stayed, refusing to leave without their pets.
The Humane Scociety and the SPCA are doing their best to rescue the animals, which include dogs, cats, horses, reptiles, and even a sea lion and a tarantula.
Web sites are being used to try to reunite pets and their owners.
And many animals are being photographed, microchipped, and documented and then shipped to shelters and foster homes in other states.
