The seven-year legal battle continues over the fate of Terri Schiavo, who has been in a vegetative state for over 15 years.
Doctors say that there is no hope of recovery.
Her parents want to keep her alive; her husband who is her legal guardian says that she would not want to be kept alive artificially.
The case is complicated and has involved state courts at several levels, both state and federal legislatures, and the governor of Florida as well as the U.S. President.
As of 19 March the feeding tube had been removed by court order.
