Reaction to Mark Felt's coming out as Deep Throat varies.
Some speculate Felt acted out of disappointment at being spurned for the position of FBI Director.
Former FBI Director Patrick Gray feels shocked and betrayed by his former deputy.
Retired FBI agent Paul Daly continues to claim first-hand knowledge that Felt did not act alone.
Felt's family admits money influenced their decision to convince him to go public.
They have book and movie deals.
In his own news article and book on the subject, Bob Woodward wrote that Felt was motivated by reverence for the FBI and disgust with Nixon.
