After a nearly two-year investigation in the CIA leak case, Lewis 'Scooter' Libby, Vice-President Cheney's chief of staff, was indicted on felony charges of perjury, making false statements to FBI agents, and obstruction of justice for impeding a federal grand jury.
Libby resigned immediately.
If convicted, he faces a maximum of 30 years in prison and a 1.25 million dollar fine.
He said he plans to fight the charges.
Karl Rove, President Bush's deputy chief of staff and close political advisor, was not indicted but still faces the possibility of prosecution as the investigation continues.
