The thinning of glaciers and ice shelves, as well as the softening of the permafrost, has accelerated greatly in recent years.
While it is not certain that the man-made greenhouse effect is entirely to blame, it is clear that man must take steps now to address the problem.
Global warming affects everything: oil-platforms, the society of peoples who are indiginous to the polar regions, polar animals, migratory birds, lakes (which are drying up as the permafrost melts), and even tourism.
As melting cold fresh water enters the salty sea, it will affect ocean currents and therefore world climate.
