Iraqi Christians who are increasingly targeted by insurgents are leaving Baghdad for the Kurdish north, Syria and Jordan.
The move is temporary because they aren't selling their homes and property.
About 15,000 of Iraqi nearly 1 million Christians have left the country since August 2004.
Insurgents abducted a Syrian Catholic Archbishop apparently to frighten Iraqi Christians in upcoming elections.
Former Archbishop of Canterbury launched a campaign to assure the future of Iraqi Christian community.
Their rights should be enshrined in the new Iraqi constitution and financial aid given for return to their lands and homes.
