Chinese coalmines are said to be the most dangerous in the world.
January-September 2005 there were 2337 coal-mine accidents killing 4228 people, up 8.5 percent from the rate in 2004.
Accidents included explosions, floods and cave-ins.
The Chinese government has issued mine-safety regulations, but enforcement is ineffective.
Mines are shut down for violation of regulations, but the demand for coal is great and many mines owned by local officials quickly reopen without sanction.
In August 2005 the government ordered all officials with coalmine investments to withdraw their stakes.
