Christians in Mosul protested polls not opening for "security reasons", keeping 200,000 from voting.
Christians won one National Rafidain List seat in the new National Assembly and five spots on Kurdish and PM Alawi tickets.
Christians demand the new constitution not be based solely on the Koran and include religious freedom.
A Christian police general was assassinated in Kirkuk and four Christian women were murdered in Baghdad.
Catholics celebrated a mass for Pope John Paul II.
Christmas celebrations became low-key.
The Roman Catholic community in Baghdad fell from 60,000 to 5,000.
A bombed church was rebuilt with a high wall.
