The largest passenger airliner ever built, the Airbus 380(A380), took off on its maiden four-hour flight on April 27, 2005 in France.
The European company, Airbus, is the newest competitor with the Boeing Company.
The A380 is designed to carry 555 passengers, but can be expanded to 800 seats.
Airbus stresses the plane's fuel efficiency.
Its first test flight was successful.
Orders for 149 aircraft from airlines and freight companies have been received.
No US airline has ordered the jet yet.
First commercial deliveries to Singapore Airlines are scheduled for 2006.
