Several international meetings have been held to address the issues of global warming and climate change.
There continues to be disagreement on whether or not this is the effect of human activity, although scientists agree that something has changed radically and that there are few other explanations.
New satellite photos show that Arctic ice is melting faster than before and that air temperatures are rising sharply.
And two explorers working with Greenpeace could not complete a trip from Siberia to the North Pole because of the effects of rising temperatures, including broken ice, strong currents, and heavy rainfall.
