Rescue efforts continue for pets abandoned in the wake of Hurricane Katrina.
Some are still found alive, but estimated tens of thousands have already died.
By 10 October, some 8,000 animals have been rescued.
At least 600 have been reunited with their owners.
Tens of millions of dollars have been donated for Katrina animal rescue.
Animals have been sent from the Lamar-Dixon shelter and another at Louisiana State University to smaller shelters, foster homes and even prisons across the country to await reunions or adoption.
Lamar-Dixon will be shut down on 15 October.
Petfinder.com will list pets through 15 December.
