Calls for help have increased sharply since enrollment for Medicare Part D opened.
Many organizations and volunteers try to supplement the swamped Medicare lines, but all face developing backlogs and problems training personnel.
The multiplicity of options, deductibles, premiums and exceptions make comparisons overwhelming if not impossible.
Some lawmakers are suggesting a two-year delay in implementation of the plan.
One week into open application, The New York Times declared Part D as an attempt to do something about drug costs for seniors and at the same time protect drug and insurance companies.
"It's a mess.
It's hopelessly confusing."
