Terri Schiavo died on Thursday 31 March, thirteen days after her feeding tube was removed by court order.
Her husband has requested an autopsy.
In the final two weeks of Schiavo's life, at least 47 protestors were arrested and there were numerous appeals to have the tube reinserted.
Efforts even included a congressional bill to shift jurisdiction from state to federal courts and President Bush's rush back from Texas to sign that bill.
In Florida Governor Bush tried to get custody transferred to the Florida government.
And the case bounced back and forth in state and federal courts.
