Benefits from the Medicare Part D prescription drug program will not begin until January 1, 2006, but Medicare beneficiaries may sign up beginning November 15, 2005.
The choice is difficult - not just whether to join, but which of a multitude of plans is best for an individual.
Choice of the wrong option can endanger benefits already provided by Medicare or other programs.
The problem is so baffling that Medicare has established a hotline and a website to help applicants, but users complain that the website is ponderous and the representatives on the hotline are often misinformed.
