In early June a retired FBI official claimed that several other bureau officials "all since deceased" had collaborated with Felt in his role as "Deep Throat".
On June 6 Mark Felt's daughter acknowledged that money played a role in the family's decision to go public.
It was announced on June 15 that the Felt family had chosen a publisher for a book to be released next spring and given movie options for the Felt life story.
On July 5 Bob Woodward's book "The Secret Man" appeared in stores revealing more details of Felt's role as "Deep Throat."
