Terri Schiavo died 13 days after her feeding tube was removed by order of a Florida state court judge.
Her parents continued to fight to keep their daughter alive.
A federal judge refused to order Terri Schiavo's feeding tube reinserted.
President Bush signed an unprecedented law to avert her death.
Florida lawmakers refused to intervene in her case.
An appeals court and US Circuit court also ruled against her family.
The US Supreme court turned aside the case of Terri Schiavo.
