A report in Vanity Fair identifying 1972-73 Watergate leaker "Deep Throat" as the FBI Deputy Director W. Mark Felt, was verified by Felt's grandson on May 31, 2005.
Felt is now 91 and in ill health.
Editor Bradlee and reporters Woodward and Bernstein of the Washington Post who had kept the secret for over 33 years quickly confirmed the identification.
After years of speculation individuals expressed dismay, condemnation, praise and "I told you so"!
On June 2 it was announced that Bob Woodward's book on "Deep Throat" would be published in July.
