China's accident-plagued coal mines cause thousands of deaths and injuries annually.
2004 saw over 6,000 mine deaths.
January through August 2005, deaths rose 8.5% over the same period in 2004.
Most accidents are gas explosions, but fires, floods, and cave-ins also occur.
Ignored safety procedures, outdated equipment, and corrupted officials exacerbate the problem.
Official responses include shutting down thousands of ill-managed and illegally-run mines, punishing errant owners, issuing new safety regulations and measures, and outlawing local officials from investing in mines.
China also sought solutions at the Conference on South African Coal Mining Safety Technology and Equipment held in Beijing.
