Michael Schiavo won a malpractice suit concerning Terri's coma in 1993.
He first petitioned for feeding tube removal in 1998.
After final tube removal in 2005, US District Court Judge James Whittemore refused to order reinsertion.
The parents appealed to a three-judge federal appeals panel but were rebuffed.
Judge Greer issued an injunction keeping the DCF and police away from Terri.
Courts consistently rejected appeals related to abuse allegations or new medical diagnoses, and efforts to block Terri's cremation.
The US Supreme Court again declined involvement.
A federal appeals court agreed to consider a new hearing but Terri died first.
