In 1994 Airbus began engineering the A380, a superjumbo airliner larger than Boeing's 747.
Component production started in 2002 in Germany and France.
A Toulouse, France assembly line opened in 2004.
Parts were pared down and new materials introduced to keep the plane at target weight but sent the plane over budget.
The A380, carrying between 555 and 840 passengers, was unveiled in January 2005 and test flown in April.
Airports need to make design changes to accommodate this overlarge plane that boards on two levels.
The US objects to government subsidies to Airbus and airport neighbors complain about noise.
