Five thousand pets have been rescued but time is running out for the rest.
Many animals are sick from consuming contaminated water, garbage and carrion.
LSU's Parker Coliseum (Baton Rouge) houses over a thousand rescued pets and Lamar-Dixon expo center (Gonzales) holds up to 2,000, including larger and sicker animals.
Staff are from the Humane Society, US Public Health Service, FEMA, and volunteers.
Pets are sent to smaller shelters, foster homes, and prisons for longer-term care.
Over 600 have been reunited with owners.
Rescuing people takes priority but the Humane Society and a bill in Congress urge pet evacuation also.
