US members of the Iraqi Christian minority living in the US voiced hope for national unity in Iraq's first free elections.
Hundreds of Iraqi Christians protested voting irregularities outside of Baghdad's Green Zone.
Many polling places opened late or never opened.
Those that opened didn't have ballots or election material.
Although not written yet, Iraqi Christians fear that the new constitution will favor Islam over Christianity.
More killings of Christian Iraqis occur including a Christian general.
Yet, they celebrate Christmas and some hope to flee Iraq.
