Christians make up about three percent of Iraq's population.
Since the U.S.-led war started, armed attacks have led many to leave the country, mostly for neighboring Syria and Jordan.
Several churches in Baghdad and Mosul have been attacked and more than 100 Christians have been killed, with many more wounded.
Those targeted have included people helping the U.S.-led forces, as well as those in occupations seen as breaking Islamic law, such as owners of liquor-stores and beauty parlors.
In mid-January, just before the upcoming elections, a Catholic archbishop was kidnapped by gunmen in Mosul.
