In 2005 the A380 was six months behind schedule and owed millions in buyer compensation.
Customized cabins and entertainment system installation problems caused delays.
France called unreasonable a US-proposed safety review to determine whether A380 turbulence would require greater distances around the plane.
Airbus raised the A380's price by $10 million.
A wing ruptured during a February 2006 stress test but the plane qualified in emergency evacuation, an important step towards certification.
Airbus was approaching its break-even point of 250 plane sales.
Twenty airports would be ready for A380s in 2006, with Singapore Airlines being first to fly the plane.
