Climate change could thaw the top 11 feet of permafrost in most areas of the Northern Hemisphere by 2100 altering ecosystems across Alaska, Canada and Russia according to a US study.
If this occurs, considerable amounts of greenhouse gases could be released into the atmosphere, which could amplify global warming.
However, another researcher disagrees that the thaw would be so large.
He states that Alaska's permafrost won't melt that fast or deep.
A group of countries, which fringe the Artic waters, met to discuss measures to reduce greenhouse emissions.
