Terri Schiavo's husband and legal guardian Michael Schiavo is involved in a seven-year court battle with her parents.
Mr. Schiavo has fought for legal permission to remove her feeding tube, which has kept her alive for 15 years.
Some doctors testified that Terri Schiavo is in a persistent vegetative state after a sudden heart attack, with no hope for recovery.
Her parents insist that she be kept alive.
She had no living will or written instructions.
The legal battle in Florida is complex.
A judge instructed that the tube be removed on March 18, 2005.
