Michael Schiavo's legal battle to have his long-comatose wife Terri's feeding tube removed against her parents' wishes began in 1993.
Courts ordered it removed in 2000 and 2003.
Six days after a 2003 removal it was reinserted after Governor Jeb Bush pushed "Terri's law" through the Florida Legislature.
Florida's Supreme Court struck this down as unconstitutional.
The US Supreme Court declined to get involved.
Florida Judge George Greer ordered the tube be disconnected on 3/18/05, rebuffing US congressional intervention efforts as having no jurisdiction.
Congress then passed narrow legislation allowing Terri's parents to appeal to federal courts for tube reinsertion.
