In January elections, Christians won only six seats in the new National Assembly.
Outside the Green Zone Christians protested voting irregularities.
The 71-member committee drafting the constitution included only one Christian, leading to fears that the document would not recognize minority religious rights.
Christians gathered under police protection for a special mass for Pope John Paul II.
But violence continued.
A Christian police general was killed in Kirkuk.
Gunmen killed four Christan women in a Baghdad Christian neighborhood.
And some churches were surrounded by tall walls and guarded with rifles.
For safety, Christmas midnight mass was held in daylight.
