Assyrian Christians in Iraq date to the pre-Islamic first century.
Modern day Christians have represented three percent of Iraq's population.
Muslims regularly persecuted Christians, intent on driving them out.
Iraqi Christians' future looked brighter after Saddam's fall but now looks worse, even though freedom of religion was stipulated in the interim constitution.
Since the war began, over 100 Christians have been killed.
Militants target Christians and try to shut their worldly business and keep them from voting.
Fifteen thousand Christians have left Iraq.
Twelve churches were bombed.
The Chaldean patriarch's home was attacked and Mosul's Archbishop Casmoussa was kidnapped.
