Tens of millions of dollars have been donated to pet charities because of Hurricane Katrina, but weeks after the storm, abandoned animals are still a major concern.
It is estimated that more than 50,000 pets were left behind.
Hundreds arrive at shelters every day, most suffering from at least one ailment, such as dysentery, infection, malnutrition, dehydration.
Many died before they could be rescued.
Local shelters are overwhelmed, so some animals are being sent to shelters and foster homes in other states.
Two prisons have taken in animals, which the inmates will care for until permanent homes can be found.
