Pluto, discovered in 1930, was named the ninth planet because, though small, it is round like other planets, and has an atmosphere, seasons, and moon.
Astronomers now debate downgrading Pluto to Kuiper Belt Object (KBO) because of its similarity to other icy bodies orbiting beyond Neptune.
KBOs are being accurately studied by the orbiting Spitzer Space Telescope.
A possible new planet in 2005 is 2003 UB313 (2003 EL61), nicknamed Xena.
Spanish astronomers also allege the discovery.
"Planet" has no official definition.
Xena is similar to Pluto, has a moon, also orbits at an angle, and is twice Pluto's size.
