On the night of Nov. 9, 2005 the level of violence throughout France showed the first signs of abating.
More than 11,500 police and gendarmes in 300 cities and towns had been mobilized.
Residents, police and firefighters suffered one death and more than 115 injuries.
More than 7500 vehicles were torched.
Although the riots were ignited by the accidental electrocution death of two teenagers, President Chirac acknowledged that France must confront inequalities and discrimination among its African and Muslim minorities that fueled the unrest.
On Nov. 14 emergency powers were extended for three months.
