On Jan. 19, 2005 South Ossetians abducted two Georgian police officers in an attempt to disrupt any peace talks.
In Abkhazia the new elected president pledged to fight on for international recognition of its de facto independence.
On Jan. 26 Saakashvili's offer of autonomy was immediately rejected by South Ossetia.
Saakashvili then turned to the international scene presenting Georgia as a force for liberty and freedom as opposed to the separatist regions which "are the last razor-sharp splinters of the Soviet Empire".
As of May 2005 Abkhazia and South Ossetia were still independent from Georgia.
