The killer of Judge Lefkow's husband and mother, Bart Ross, killed himself on 9 March with a single shot to the head when he was stopped for a routine traffic violation.
In his van was a suicide note linking him to the murders.
He had pursued a decade-long malpractice suit over severe disfigurement resulting from treatment for a cancerous jaw, a suit Lefkow had dismissed a number of years ago.
He wrote that she was "No.
1 to kill" because she had "finished me off".
He had a hit list of 25 other judges, lawyers, and doctors.
