On April 21, 2005 the Senate Judiciary Committee voted to revive the long dormant nomination of Janice Rogers Brown of the California Supreme Court to the U.S. Circuit Court of Appeals in the District of Columbia.
Brown's nomination had been blocked by Democratic filibuster during President Bush's first term.
Senate leaders began negotiations over various compromise proposals on handling judicial nominations with the Republican leaders threatening to rule out the filibuster.
By May 17 it appeared that Brown's nomination would not reach the Senate floor for another week or perhaps not until after Memorial Day.
