Bart Ross, 57, was pulled over by police in a Milwaukee suburb for a defective taillight.
Ross immediately committed suicide with a shot to his head.
In his van was a letter describing how after treatment for mouth cancer left him disfigured, Judge Lefkow and others ruined his life by dismissing his medical malpractice suit.
He vowed to kill them.
On February 28th he hid in a Lefkow closet waiting for the judge, but her family found him first so he killed them instead.
DNA from a cigarette butt in the home matched Ross's and he resembled a composite sketch.
