Libyan leader Moammar Gadhafi, called for a Darfur mini-summit to be held on October 21, 2004 in Sirte, Libyan.
Gadhafi invited the presidents of Sudan, Egypt, Chad, Nigeria and the leaders of Darfur's two rebel groups.
Talks between Darfur rebels and the Sudanese government were held in Abuja, Nigeria in August and September 2004.
The next round of talks will be held as part of the Darfur mini-summit, which was switched to Tripoli.
This was done to obtain cooperation from neighboring countries, which is crucial to lasting peace.
