Major concerns have arisen over the leadership and credibility of Fannie Mae's CEO Franklin Raines.
The regulatory agency known as OFHEO conducted the Initial investigations into Fannie Mae's accounting practices and found that the company had violated accounting rules to present a picture of financial well-being and to maximize executive bonuses.
Raines has had to testify before the House Financial Services Committee.
The Justice Department is conducting an investigation.
The SEC has opened an inquiry into company accounting practices.
The U.S. attorney's office is pursuing a criminal investigation.
And eight lawsuits have been filed on behalf of shareholders.
