Democrat Christine Gregoire was sworn in as governor of Washington state on 12 January after an extremely close election.
The Republicans sued to overturn the gubernatorial election, charging election fraud.
A judge dismissed the lawsuit on 6 June, asserting that there were human errors but no fraud, and Republican Dino Rossi decided to end his 5-month legal fight.
Gregoire was declared the winner in late June by the Washington Secretary of State.
Meanwhile, by the end of the month Rossi vowed to continue his fight and called for a new vote.
