Mikhail Saakashvili won the presidency of Georgia in Jan. 2004 vowing to regain the separatist regions of Abkhazia, South Ossetia and Adzharia.
He was successful in restoring Adzharia but has made little headway in the other two.
In May he sent troops into South Ossetia culminating in an indecisive temporary cease-fire agreement in August.
The same month he threatened ships bound for Abkhazian ports.
He offered "the wildest possible autonomy," but his bid to open talks was rejected by the Abkhazians.
By Jan. 2005 he was promising official proposals to the two by the end of the month.
