Saakashvili's priority is to reunite pro-Russian separatist regions with Georgia.
He succeeded in Adzharia, but not in Abkhazia and South Ossetia.
Saakashvili has sent troops to the regions during times of heightened tensions and engaged in on-again off-again negotiations with the self-proclaimed governments.
He ordered Georgian authorities to screen ships arriving in Abkhazia, threatened to sink Russian tour boats, and had coast guards fire on a Turkish ship.
He closed down South Ossetia's trade in smuggled Russian goods.
Saakashvili is seeking better relations with Moscow to improve relations with the renegade regions, and will soon present official proposals to them.
