Rioting by young Muslim men broke out in a Paris suburb on the night of Oct. 27, 2005.
Cars were torched, windows smashed, and policemen stoned.
On successive nights the rioting spread to other parts of Paris and then to other cities.
Thousands of police have been deployed to little avail.
Fortunately casualties have been light.
Some rioters blame the unrest on tough policing policies but it is more likely caused by frustration of young men who have no work and little hope for the future.
On Nov. 8 the French government authorized local authorities to impose curfews.
