The Lefkow murder investigation took a surprising turn when Bart Ross committed suicide at a traffic stop on March 9, leaving a handwritten confession in his car.
Later that day, a local TV station receive a typed suicide letter, dated February 13, which included a hit list of judges, lawyers and doctors and a handwritten account of the Lefkow killings.
Ross felt he was a medical malpractice victim and spent over a decade unsuccessfully pursuing lawsuits.
Judge Lefkow, who recently ruled against Ross, was his primary target the day of the killings.
DNA evidence confirm he was the killer.
