North Korea withdrew from the Nuclear Non-Proliferation Treaty after the United States accused the country of having a nuclear weapons program based on enriched uranium.
North Korea declared in February 2005 that it has already built nuclear bombs.
Since 2003, the six-nation (United States, North Korea, South Korea, China, Japan and Russia) talks have aimed at persuading North Korea to abandon its nuclear weapons in exchange for diplomatic and economic benefits and security guarantees.
