As the Senate debated the issue of filibustering judicial nominations, a bipartisan group of centrist senators kept working on possible compromise solutions.
On May 23, 14 moderate senators announced an agreement under which Democrats would vote to end debate on three nominations including Brown's, while Republicans agreed to oppose any attempt to change filibuster rules.
On June 6 debate on Brown's nomination opened with Republicans praising her great talent while Democrats deemed her an extreme conservative ideologue.
On June 8, 10 Democrats joined Republicans to close debate and the Senate voted 56-43 to confirm Brown.
