The race for to be governor of Washington state was extremely close.
The initial count showed the Republican candidate, Dino Rossi, ahead by 261 votes out of 2.9 million.
The first recount, done by machine, showed him ahead by only 42 votes.
The second recount, done by hand, gave Democrat Christine Gregoire a 120-vote lead and she was declared the winner on 30 December, fifty eight days after the election.
Rossi has filed a lawsuit, alleging that dead people, felons, and other ineligible voters cast ballots and demanding an unprecedented statewide re-vote.
The inauguration may be postponed.
