The SEC ruled that Fannie Mae had overstated its profits by 38 per cent in the years 2001-2004.
The OFHEO held Raines responsible the company's emphasisis on earnings over accuracy and demanded significant changes in senior management.
On 21 December, Raines took early retirement with millions of dollars in benefits and stock, plus an annual pension of over one million dollars.
The company still faced a Justice Department criminal investigation, an SEC civil investigation, further OFHEO examination of its accounting, and several class-action lawsuits.
As of 21 January, Fannie Mae was withholding millions in bonuses for top executives.
