Talks with North Korea end with the signing of a joint statement.
The document states that North Korea agrees to abandon its nuclear weapons programs and return to the Nuclear Non-Proliferation Treaty in return for recognition of its right to nuclear energy.
It also agrees to submit to International Atomic Energy safeguards.
China, Russia, South Korea, Japan and the US give North Korea energy assistance and agree to discuss giving a light-water nuclear reactor for generating electricity.
North Korea won't dismantle its nuclear program until it receives the reactor.
