Several rounds of six-party tallks on North Korea's nuclear program have broken down since August 2003 without an agreement.
South Korea, the U.S., Japan, China, and Russia want North Korea to abandon its development of nuclear weapons.
Pyongyang insists on having nuclear power for peaceful purposes, something opposed by the U.S. South Korea has promised massive aid to North Korea, including electricity, rice, and other necessities, if an agreement can be reached within the six-party framework.
It has also suggested a rehabilitation program for the North, a proposal that the U.S. and Japan strongly oppose.
