The six-party talks aimed at getting North Korea to abandon its nuclear programs resumed 13-19 September.
Pyongyang pledged to abandon its nuclear programs, to rejoin the Nuclear Non-Proliferation Treaty, and to follow IAEA safeguards in return for a pledge of aid and security.
The U.S agreed not to attack North Korea.
China, Russia, South Korea, the U.S., and Japan agreed to give North Korea energy assistance including a light-water reactor.
But the deal fell apart almost immediately, when Pyongyang insisted that it would not dismantle its nuclear weapons program until the reactor was built.
