Christine A. Gregoire was sworn in as the new governor on Jan. 12, 2005.
In the first action on Dino Rossi's lawsuit to oust Gregoire the Judge declared that his courtroom and not the Democratic-controlled legislature was the proper forum to investigate the election.
The case was scheduled to go to trial May 23.
Although Democrats acknowledged human errors in vote counting, they vigorously denied Republican charges of fraud.
The lawsuit was dismissed on June 6 for lack of evidence and Rossi did not appeal to the Supreme Court.
