A committee of the International Astronomical Union (IAU) is considering the question of planethood of Pluto and 2003 UB313 (Xena).
Both might be called "minor planets" or could be considered KBOs.
NASA's Hubble Space telescope strengthened Pluto's claim to planethood by finding its second and perhaps third moon.
On Jan 20, 2006 NASA launched its New Horizon spacecraft to explore Pluto and the Kuiper Belt which it is scheduled to reach in July 2015.
Meanwhile German astronomers determined that the diameter of 2003 UB313 is 1800 miles compared to Pluto's 1380.
The IAU committee continues to deliberate.
