Gregoire was sworn in as governor and proceeded to govern as if elected by landslide, imposing taxes and improving roads.
Rossi sued for a revote in Republican-leaning, rural Chelan County, claiming illegal votes by felons and ballot-box stuffing.
Most Washingtonians opposed a revote.
Constitutional language on contested races was ambiguous.
Judge John E. Bridges heard the case without a jury.
He dismissed the lawsuit because Rossi's lawyers failed to meet their burden of proof.
Most of the proved illegal votes by felons were for Rossi.
Rossi ended his efforts to remove Gregoire, who was certified as governor-elect in June 2005.
