A French newspaper accused Lance Armstrong of using the illegal performance-enhancing drug, EPO in 1999 to win his first of seven consecutive Tours.
The laboratory conducting the tests couldn't confirm the samples were Armstrong's, but the newspaper said it decoded the labels from samples identifying Armstrong.
Armstrong strongly denies this charge.
The director of UT's Human Performance Laboratory, who studied Armstrong's physiology from 1992 to 1999, stated that Armstrong's record winning streak is explained by his years of training and a modest diet in the spring months before the Tour de France.
