On Sept. 9, 2005 the International Cycling Union (UCI) said no action would be taken against Armstrong.
On Sept. 21 the IOC Athletes Commission and the Summer Olympic sports demanded suspension of the French laboratory that accused Armstrong, claiming that its tests were illegal.
The charge was made in a letter to the World Anti-Doping Agency President, who replied that the laboratory did not appear to have broken any ethical rules.
On Oct. 6 the UCI President called for an independent investigator to look into the Armstrong matter in case ongoing investigations by UCI and WADA reached different conclusions.
