With a state of emergency declaration, overnight curfews, and a public meetings ban, violent riots around Paris and throughout France steadily abated.
The situation markedly improved by the 18th night.
The French cabinet extended emergency police powers for three months to ensure an end to the riots.
Some 300 towns and cities were affected and around 11,500 anti-riot forces were mobilized.
Damages and casualties were considerable.
Over 115 citizens, police officers and firefighters were injured, as were three foreign reporters.
A rioter lost a hand throwing a Molotov cocktail.
Over 7,500 vehicles were torched and dozens of buildings destroyed.
