Franklin Raines, the chairman and chief executive of Fannie Mae is defending its accounting practices and disagrees with allegations that it violated rules to maximize executive bonuses.
Fannie Mae will be investigated by the Justice Department and the Securities and Exchange Commission (SEC) and faces litigation by shareholders.
Raines and other executives could not only lose their jobs, but also face fines and prison for knowingly certifying false financial statements.
They can be compelled to give back incentive pay and gains from sale of stock.
