Until the last days of the campaign, State Attorney General Christine Gregoire (Democrat) was favored to win Washington's 2004 governor's race over wealthy real estate agent Dino Rossi (Republican).
Absentee ballots postmarked by Election Day trickled in.
Rossi led by 261 votes, triggering a recount required by law if the margin is less than 2000.
Following a machine recount, Rossi led by 42 votes.
A third count, by hand, took place after Democrats raised sufficient money.
Election officials discovered over 700 erroneously rejected or misplaced absentee ballots.
Seven weeks after Election Day, Gregoire led by 130 votes, reversing election results.
