Riots erupted after the accidental electrocution deaths of two youths hiding from police they mistakenly thought were pursuing them.
The incident sparked an ever-escalating 12 nights of violence which spread through Paris suburbs and into the city.
Rioters torched hundreds of cars nightly, burned and vandalized buildings, injured dozens of police officers and firefighters, set a handicapped woman afire and beat a man to death.
French officials appealed for calm and eventually imposed curfews to restore order.
The rioters are French-Arab and French-African young men, frustrated by economic misery and racial discrimination and stigmatized by a new tough anti-crime initiative.
