Lance Armstrong continues to vehemently deny doping charges.
The IOC president called for an independent investigation into allegations he used EPO in 1999.
He questioned the integrity and validity of the tests and demanded the laboratory be suspended.
The International Cycling Union and the World Anti-Doping Agency both announced separate inquiries.
UCI and WADA have been feuding over the case.
UCI accused WADA of withholding information.
WADA accused former UCI president Verbruggen of leaking documents to L'Equipe.
