Averting a showdown, Senate Democrats and Republicans finally reached a compromise which cleared the way for confirmation votes on California Supreme Court Justice Janice Rogers Brown's nomination to the US District Court of Appeals for the District of Columbia.
After stalling Brown's nomination with a 2-year filibuster threat, Democrats agreed to vote for cloture, ending the debate on June 7.
Republicans agreed not to force a change in the application of Senate filibuster rules by the so-called nuclear option.
On June 8, Janice Rogers Brown won confirmation.
