The long-dormant and controversial appeals court nomination of Janice Rogers Brown will soon go before the Senate.
Republicans plan to use a parliamentary maneuver called the nuclear option that would effectively outlaw filibusters.
Moderate Democratic and Republican senators have been trying to work out a compromise that would enable confirmation votes to move forward without such a rule change, so far unsuccessfully.
Democrats oppose her nomination, claiming she would advance extremist conservative views, particularly on issues regarding parental notification of abortions for minors.
Republicans claim she is independent and hard-working, with an open mind and a lot of common sense.
