Scientists debate redefining "planet" or retiring the term.
KBO 2003 UB313, discovered by Michael E. Brown, was confirmed by surface heat emanations to be 30 percent larger than Pluto.
Both have surface methane ice.
If Pluto is a planet, 2003 UB313 should be too.
The Hubble Space Telescope showed two more small moons orbiting Pluto, 30-100 miles in diameter.
Pluto and its large moon Charon, close physically and in size, may be a binary planet system orbiting a center mass between them.
At least four KBOs have known moons.
Pluto would be the first KBO to have multiple satellites.
