The husband and mother of U.S. District Judge Joan Lefkow were killed in the basement of her Chicago home on 28 February.
Investigators found a bloody footprint and fingerprints butts at the scene.
There are no suspects.
Investigators have questioned relatives, friends, and supporters of Matthew Hale, the leader of a large white supremacist group, who was convicted last year of obstruction of justice and of ordering Lefkow's killing.
They also want to question two men seen in a car illegally parked near the home that afternoon.
A $50,000 reward has been offered for information in the case.
