In the Nov. 2, 2004 election for Governor of Washington, the first vote count showed Republican Rossi leading by 800 votes.
The following day Democrat Gregoire led by 1400; the next day Gregoire by 21,234; and by Nov. 16 Rossi by 19.
By Nov 18 all votes were counted and Rossi led by 261.
A machine recount gave Rossi a 42-vote edge but a manual recount gave Gregoire a lead of 261.
On Dec. 30 Gregoire was declared Governor-elect.
On Jan. 7, 2005, with inauguration scheduled for Jan. 12, Rossi filed a lawsuit seeking a new election.
