Judge Joan Humphrey Lefkow's husband and mother were murdered in their home on February 28.
They died of multiple gunshot wounds between 10:30 a.m. and 5:30 p.m.
Evidence being analyzed includes broken window glass with a fingerprint, a bloody footprint,.22-caliber shell casings, a bloody mop and cigarette butts.
Investigators released composite sketches of two men seen near the home on the day of the killings.
A $50,000 reward is being offered for leads in the case.
The prime suspect is domestic extremist Matthew Hale, convicted last year of soliciting her murder.
He and his supporters deny any involvement .
