The directors of Fannie met on Dec. 19 to decide Raines' fate, but the meeting concluded without any announcement of a decision.
On Dec. 21 Raines resigned with his departure structured as an early retirement.
The directors' decision in favor of Raines' retirement rather than dismissal would reap him $8.7 million in deferred payments and an annual pension of more than $1 million.
On Jan. 21, 2005, however, Fannie announced that Raines would be denied the cash bonus that he would have received for 2004.
