Peace talks on the crisis in Sudan's Darfur region restart.
But rebel leaders pulled out of the talks accusing the government of repeatedly breaching a ceasefire agreement.
The African Union is trying to put peace negotiations back on track.
The rebels vowed never to resume the negotiation process unless the government ends its attacks and withdraws from the troubled area.
Peace talks between the Sudanese government and the rebel groups have been suspended until January 2005.
