On August 23, 2005 the French Sports newspaper L'Equipe charged that Lance Armstrong used the drug EPO in 1999.
Armstrong strongly denied the charge.
The French sports minister, the Tour de France director and the chief executive of the USCycling said that since the tests used as a basis for the charges were inadequate no action would be taken against the cyclist.
A Texas scientist attributed Armstrong's performance to his modern training approach, not EPO.
A specialist in the fight against doping in sports, however, suggested that Armstrong had used a range of banned substances.
