Astronomers have questioned whether Pluto is a planet or a Kuiper Belt Object (KBO), one of a belt of comets, asteroids and other objects at the edge of the solar system.
Then on July 29, 2005 Caltech astronomer Michael A. Brown announced discovery of a new body designated 2003 UB313 which is larger than Pluto with a surface very similar to Pluto.
The question: is UB313 the tenth planet or should it and Pluto both be considered KBOs?
On Sept. 10, Brown announced that UB313, which he considers a planet and has nicknamed Xena, has a moon.
