The International Cycling Union (ICU) gave Lance Armstrong major support in his fight against doping allegations.
An ICU statement said no action would be taken against Armstrong over claims that his 1999 urine samples tested positive for EPO.
The ICU found no wrongdoing and no reason to condemn him.
The IOC Athletes Commission and the Summer Olympic sports (ASOIF) have demanded the French lab that tested Armstrong's urine be suspended.
The World Anti-Doping Agency (WADA) insists the lab broke a host of rules set down by the WADA Code.
