On Sept. 22, 2004 the Office of Federal Enterprise Oversight cited numerous accounting irregularities in mortgage giant Fannie Mae (Fannie) headed by Franklin Raines.
It was charged that earnings were doctored to inflate executive compensation.
Raines could possibly face not only loss of his position, but fines and prison for falsifying financial statements.
On Dec. 15 the Securities and Exchange Commission concluded that Fannie had indeed violated accounting rules.
Lawmakers called for return of millions in executive bonuses.
Raines received $14 million in salary and $25 million in incentive pay 2001-2003.
Raines defended Fannie's accounting.
