Raines testified to Congress that he expected to be held accountable if his interpretation of the accounting rules was not accepted.
The chief accountant of the SEC ruled that Fannie Mae violated accounting standards overstating its profits by 38 percent since January 2001.
Raines is seeking a vote of confidence from the directors as he struggles to survive criminal investigation.
Raines retired under pressure from federal regulators.
Raines will be denied bonuses for 2004 as Fannie Mae eliminated bonuses for top executives.
