French newspaper L'Equipe reported new tests by a French laboratory on backup urine samples Lance Armstrong provided at the 1999 Tour de France tested positive for EPO.
Armstrong strongly denied the charges and questioned the validity of the tests.
USA Cycling, fellow cyclists, scientists and French fans have defended Armstrong.
Defenders attacked the report as unethical and the laboratory results as flawed and unsound.
Armstrong is suing a British newspaper for printing excerpts from a book which insinuated he had been doping.
An Italian specialist believes Armstrong used other drugs, too.
However, he has never been found guilty of doping.
