Saakashvili told European parliamentarians he would give more independence to separatist regions, as long as Georgia remains whole.
South Ossetia immediately rejected his offer of autonomy.
Peace talks broke down when two Georgian police officers were abducted and 12 Ossetians were abducted in response.
Georgian and Abkhazian officials met with a UN envoy to discuss security issues and agreed to meet again in mid-June.
Saakashvili discussed the issue with President Bush.
He called for a new Yalta conference to extend the rule of liberty throughout the Black Sea region.
Saakashvili and the Moldovan president issued a joint declaration against separatism.
