Scientists say reversing childhood obesity requires wide-ranging efforts.
Less time should be spent in front of the computer and television.
Schools should remove junk food from vending machines and reduce the fat in cafeteria lunches.
Experts recommend reducing sugar consumption.
Changes need to be made in food labeling and advertising as well as more school and community recreational facilities and physical education programs.
Trainers can help kids who don't enjoy organized sports or who are embarrassed doing active things with fitter kids.
