A small Russian submarine with seven crew members was trapped on the seabed off the Kamchatka Peninsula late on 4 August.
The Russians tried desperately to pull the sub to shallower waters but those efforts failed.
They sought international assistance.
Japan sent four naval vessels, the U.S. sent three underwater vehicles, but the British were the first to arrive, with remote control submersibles.
They cut away the net or undersea cables trapping the sub, enabling it to rise to the surface after almost three days at the bottom.
All seven crew members were alive and well.
