Martha Stewart spent Halloween, Thanksgiving, Christmas and New Year's in prison.
Her job there was cleaning.
During her stay, she did ceramics, crocheted, taught yoga, decorated the chapel for a memorial service, became an expert on vending-machine snacks, and foraged the grounds for fresh greens for the prison salads.
She was grateful for the support of her friends, family, colleagues, and fans.
Stewart became a prison reform advocate through her experience.
She emerged from the Alderson prison on March 4 with head held high, 20 pounds lighter and a lot wealthier, since shares in her company nearly tripled in value.
