Breast cancer survival rates have improved because of better screening, leading to detection of smaller tumors when the cancer is still localized.
There are two new drugs for breast cancer - herceptin and avastin.
Scientists see a link between benign breast cancer lesions and later cancer.
Studies have shown that both low-fat diets and exercise can increase survival rates for breast cancer patients.
But eating french fries in childhood can lead to cancer in adulthood.
Night workers seem to have a higher incidence of breast cancer, indicating that there may be a relationship between tumor developent and exposure to light.
