Scanlon pleaded guilty to conspiring to bribe a congressman and other public officials.
His help was expected to be crucial in the Justice Department's wide-ranging Abramoff investigations.
On Dec. 28, 2005 the Justice Department was urgently pressing Abramoff to settle fraud and bribery allegations as the investigation continued.
A court date was set for Jan. 9, 2006 as Senate and criminal investigations continued.
On Jan. 3 Abramoff pleaded guilty and agreed to cooperate.
He agreed to provide evidence and testimony in the Justice Department's probe of corruption in Congress and executive branch agencies.
