Putin ordered the Defense Minister to launch an investigation.
The head of the Navy was fired.
A Navy captain was accused of damaging a Russian under-water remote-controlled vehicle in rescue attempts.
Five British, one Japanese, and two Americans were given state awards.
The seven crew members were given awards for bravery, but later accused of violating operating procedures and causing the sub's entanglement.
The Russian navy was considering buying one or two submersible rescue vessels.
The rescue cost Russia an estimated $1.5 million.
Britain, the U.S., and Japan did not charge Russia for their assistance.
