Martha Stewart arrived in good spirits for her five-month term at Alderson Federal Prison Camp.
She was treated with respect and thought inmates and officials were all nice.
She was issued clothing but could also wear an inexpensive watch and earrings.
She had one roommate in a dormitory-like building.
She exercised, took walks, cleaned toilets, read, subscribed to newspapers, watched TV news, made friends, developed innovative microwave cooking ideas for inmates, and wrote.
She kept in touch with supporters through her website and was touched by the many letters.
She played scrabble with her daughter Alexis during visits.
