In response to a call from the Institute of Medicine for a program against childhood obesity, there has been some action.
One children's TV network introduced a Saturday afternoon message encouraging children to go out and play.
Some schools have expanded physical education programs, yanked junk foods from vending machines and reduced fat in cafeteria food.
At least one YMCA has introduced a fitness room designed for pre-teens.
Congress has considered legislation to control advertising to children and Kraft Foods promised to stop TV advertising of certain products considered unhealthy to children under 12.
