Developmental drug SR-13668 curbs the oncogene protein AKT, prevalent in cancer patients; and SR-16158 reduces breast cancer patient heart disease risk.
Aromatase inhibitors lessen breast cancer recurrence with fewer side effects than tamoxifen.
Radiation therapy no longer carries heart disease risk.
Olive oil suppresses oncogene Her-2/neu and boosts effectiveness of antibody Herceptin.
Hypothyroidism and oral contraceptives reduce breast cancer risk.
Sisters are being studied to investigate environmental and genetic affects on cancer risk.
Deficiency in cell DNA repair-ability accelerates genetic changes leading to cancer.
Protein markers in genes help predict cancer recurrence.
Ductal lavage proved unreliable for detecting early cancer.
