Hurricane Katrina, one of the worst natural disasters, hit the southern part of the US on August 29, 2005.
The official death toll has risen to 118.
Federal Emergency Management Agency officials indicate that their costs are 2.8 billion dollars so far.
Qatar donated 100 million dollars to the victims and the Ugandan government pledged 200,000 dollars toward relief and rebuilding efforts.
This hurricane could cost the world's insurers up to 50 billion dollars as forecast by the British company Brit Insurance.
