As of 12 January, donations and pledges continued to pour in for tsunami relief.
Government donations from 42 countries exceeded $8 billion.
Australia had raised more per capita than any other country, including donations made through a telethon and a pop concert telecast simultaneously on all three TV networks.
The UN had aid commitments for $717 million for emergency relief, with Japan as the major contributor at $250 million.
Private donations reached more than $2 billion, the largest from a Canadian couple, who gave $4.1 million, which the Canadian government will match.
