The National Health Research Institute and a pharmaceutical company are testing two medications that can treat breast cancer.
One drug can curb a protein active in cancer patients and the other is less likely to trigger cardiovascular disease.
A new U.S. Sister Study will investigate genetic and environmental causes of breast cancer.
A new drug, aromatase inhibitor, appears to sharply reduce the chances of developing cancer in the other breast.
Researchers say that olive oil may help fight breast cancer.
Oral contraceptives may reduce the risk of breast cancer in high-risk groups.
