The Senate Indian Affairs Committee charged Jack Abramoff, a GOP lobbyist and fund-raiser, with running a crude extortion racket that has bilked tribes out of millions of dollars.
House Majority Leader Tom DeLay, additional congressmen and House aides are under an ethics investigation resulting from their connections with Abramoff.
His activities in the Northern Marianas are also being investigated.
Abramoff has been indicated in federal court on six counts of fraud and conspiracy and his partner, Michael Scanlon, was charged with defrauding Indian tribes of millions of dollars.
