Investigations of lobbyist Jack Abramoff and his partner Michael Scanlon by the Senate Indian Affairs Committee in 2004 resulted in other investigations.
The pair's lobbying for Indian tribes and Pacific islanders was shown to have benefitted the lobbyists and political associates while bilking the clients of millions of dollars.
The House majority leader and a congressman were implicated.
On Nov. 18, 2005 Michael Scanlon was charged with fraud and scheduled to go to court on a conspiracy count contained in a criminal information, typically a prelude to pleading guilty and giving full cooperation with government investigators.
