Former president Clinton launched a 10-year initiative to combat childhood obesity.
The initiative, a partnership with the American Heart Association, will include working with the food and restaurant industry to promote change, increasing physical activity and improved nutrition at schools nationwide.
School systems are now limiting the kinds of drinks sold to children and requiring more fruits and vegetables in school meals.
McDonald's has made a major marketing shift toward promoting healthier eating habits.
Kraft Foods has developed whole-grain versions of two of its popular cookies.
Abroad, schools in Bangkok, Thailand are banning sugary and fatty foods and drinks.
