Republican lobbyist Jack Abramoff is being investigated in connection with manipulating elections and extorting lobbying fees of $66 million from six Indian tribes related to protecting gaming franchises, and $9 million from the Northern Mariana Islands related to the textile industry.
Investigations also involve Abramoff's purchase of a gambling cruise ship company and arranging unreported golf junkets to Scotland.
Abramoff invoked the Fifth Amendment before a Senate hearing.
Also implicated are Republican Majority Leader Tom DeLay, his former aide Michael Scanlon, Ralph Reed, Representative Robert W. Ney, and David Safavian.
Safavian was indicted in connection with a golf trip.
