On May 5 UN Chief Kofi Anan announced that the UN team had verified that all Syrian troops and intelligence officials had left Lebanon, but it was reported that the team could not be certain about the intelligence operatives.
There were reports that some remained with a hit list of planned assassinations.
Syria denied the accusations.
The UN envoy had "constructive and helpful" talks with the Syrian president on June 12.
One June 23, as another UN verification team investigated, US officials expressed certainty that Syrian military intelligence operatives remained in Lebanon.
