The February assassination of former Lebanon Prime Minister Hariri put Syria under renewed pressure from the international community to abide by U.N.
Security Council Resolution 1559 and withdraw its troops from Lebanon.
The US, France and other European Union nations urged Syria to comply.
Egypt and Saudi Arabia encouraged Syria to withdraw its troops by the U.N. deadline of April 30.
Faced with a U.N. ultimatum, on April 3 Syria pledged to remove all troops and intelligence agents by April 30.
The U.N. sent a team of inspectors to verify whether the withdrawal was complete at the end of April.
