Tsunami relief efforts continue.
China's Shanxi Province provided medical equipment and cash worth $180,000.
Saudi Arabia offered the use of five aircraft and a pledge of $100 million.
Switzerland lent three army helicopters for use.
The government of the Hong Kong Special Administrative Region granted $192,000 while the Hong Kong Disaster Relief Fund Advisory Committee approved grants from five relief agencies for $2.88 million.
Australian tennis ace Lleyton Hewitt raised $31,500 auctioning off tennis rackets while Hong Kong superstar Andy Lou did likewise with stage costume for $38,000.
