Michael Scanlon pleaded guilty to conspiring to bribe public officials and agreed to pay back over $19 million to Indian tribal clients.
His possible 5-year prison sentence could be reduced should he cooperate with prosecutors.
Abramoff pleaded guilty to federal conspiracy, fraud and tax evasion charges and agreed to cooperate with investigators.
He did not identify officials by name.
The next day he pleaded guilty to fraud and conspiracy in Florida.
Panicked lawmakers, including President Bush, rushed to distance themselves from Abramoff by returning campaign money he gave them.
The money is being returned or redirected to charities.
