Hurricane Katrina hit the Gulf Coast on 29 August.
By 9 September the official death toll had reached 118, including one Guatemalan woman who lived in New Orleans.
Fifty other Guatemalans were missing.
FEMA's mission expenses were close to $3 billion as of 6 September.
Insurers, inclduing Lloyd's and Brit Insurance, estimated that their costs would reach $50 billion.
Damage included offshore energy installations, as well as property damage and business interruption.
Qatar was donating $100 million for the victims of the hurricane.
Uganda had pladged $200,000 for relief and rebuilding.
