At Alderson Martha had time to think, became a more sympathetic character, and got wealthier as her company's share price tripled.
Her family visited at Thanksgiving.
Martha's prison job was cleaning, sweeping, vacuuming and raking leaves.
Via her website Martha received 15,000 fan e-mails, and said she was safe, fit and healthy but found the loss of freedom and privacy difficult.
Fellow inmates shielded her from paparazzi.
She picked wild greens to augment the bad food, lost 20 pounds, learned to crochet, taught yoga, tried ceramics, decorated the chapel, ordered seeds for her garden at home, and made to-do lists.
