In December, doctors determined conclusively that Yushchenko was deliberately poisoned with the most lethal form of dioxin.
Prosecutors reopened a criminal investigation into his attempted murder.
Yushchenko was sure that Ukrainian authorities were responsible.
He fell ill on September 6, after having food and drinks with the head of the Security Service of Ukraine and others.
The Ukraine Supreme Court overturned the November runoff election results due to fraud, and Parliament enacted new anti-fraud election reforms in December.
Yushchenko won a repeat runoff on December 26 and took office in January, his face still disfigured by the poison.
