Syria's withdrawal of forces from Lebanon, required by UN Resolution 1559, Sept. 2, 2004, was not satisfied by Syria's proposal on Feb. 24, 2005 to pull back into eastern Lebanon.
The U.N. Chief, supported by Egypt, Saudi Arabia, the U.S., France and Russia, called for full withdrawal.
On March 5 the Syrian President promised pullback to the border.
A top UN envoy on March 12 demanded a full withdrawal by April 30, a position supported by the European Union.
By April 26 withdrawal was under way and the UN had sent a team to verify whether it was complete.
