On Aug. 4, 2005 the Russian navy, working desperately to disengage a small military submarine with seven crew snagged by underwater cables at a depth of 625 feet off the Kamchatka peninsula, called for international help.
Japan dispatched four vessels, Britain's Royal Navy sent a submersible Super Scorpio unmanned robotic vehicle and the U. S. Pacific fleet sent two vehicles similar to the British.
Estimates varied as to how much oxygen remained for the entrapped crewmen.
The British vehicle arrived first and on Aug. 7 the submarine was cut loose and the crewmen were found all alive.
