On Thanksgiving Day Stewart was able to enjoy a visit from her family, a privilege normally limited to weekends.
By Christmas she was calling for sentencing reform particularly for drug and first-time offenders.
By mid-January Stewart had tried her hand at ceramics and crocheting.
As she completed her term in March she was 20 pounds lighter, having taught yoga and foraged for greens on prison grounds as well as abhorring the food.
After leaving Alderson at 12:30 a.m. on March 3, 2005, Martha Steward declared the 5-month experience as "life altering and life affirming."
