Martha Stewart reported to a federal prison in Alderson, West Virginia on Oct. 8, 2004 to serve a five-month sentence.
She is very busy.
Being deluged with letters, she spends up to three hours/night at a prison typewriter.
She has some duties such as cleaning toilets but is treated with respect and spends most of her time reading and making friends.
She takes walks, goes to the gym and watches TV.
She has one roommate and is working on innovative ways to do microwave cooking to share with inmates.
Her only real complaint is the "terrible" food.
