The four bombers were British of Pakistani origin and were among the 56 killed.
The bombers left their homes in West Yorkshire and drove a rented a car to Luton, NW of London, where they met a fourth accomplice.
Closed circuit television at King's Cross caught them all chatting, then they split up.
The mother of one reported him missing after the blasts, leading to identifications and raids on five premises in Leeds, which has a large Moslem population.
The alleged bomb-builder was arrested in Egypt.
After the bombings, several arson attacks took place on mosques in northwest England.
