During the morning rush hour on July 7, terrorists exploded bombs on three London subway trains and a double-decker bus, killing at least 52 and injuring 700.
A group called Secret al-Qaida Jihad Organization in Europe claimed responsibility.
The attacks were timed to coincide with the G-8 summit meeting at Gleneagles, Scotland.
Forensic evidence indicates that each bomb contained less than 10 pounds of possibly military-grade high explosives, and all were made by a single bomb maker.
There is not yet evidence as to whether suicide bombers were involved.
Police are close to identifying someone responsible for the bus attack.
