Dr. George Bray, founding president of the North American Association for the Study of Obesity, warns that high-fructose corn syrup is a strong culprit behind childhood obesity.
Bray suggests that childhood obesity can be prevented by getting more sleep, decreasing sedentary activities, drinking more milk (calcium controls weight), thinking portion control and eating breakfast.
An Institute of Medicine report found compelling evidence encouraging the food industry to change the nature of foods being marketed to children.
Former US president Bill Clinton announced a 10-year initiative to combat childhood obesity.
