Ukrainian presidential elections were extremely close between the two leading candidates, pro-West Yushchenko and pro-Russia Yanukovich.
Runoff elections on 21 November resulted in a standoff, with Yushchenko refusing to recognize Yanukovich as President and calling for new elections, and with Yanukovich saying that he would appoint Yushchenko Prime Minister.
In September Yushchenko was treated in Vienna for a mysterious illness which paralyzed and scarred part of his face.
Supporters claimed that the illness, which occurred after a meeting with the former head of the KGB, was an assassination attempt.
Doctors said that they did not know the cause.
