The drug Herceptin will soon be added to chemotherapy as a standard part of post surgical treatment for some breast cancer patients.
Scientists reported that breast cancer patients who follow diets low in fat might reduce the chance that their tumors will return.
A study showed that walking for three to five hours per week reduced the risk of death by 50 percent.
Another study examining the role of childhood diet plays in breast cancer found an association between eating French fries regularly during the preschool years and developing breast cancer as an adult.
