In a Christmas message posted on her personal web site, Martha Stewart called for sentencing reform.
She suggested pushing for reforms in federal sentencing guidelines for nonviolent first-time offenders and particularly for drug offenders, who would be better served in rehabilitation than prison.
She is scheduled to be released in early March 2004 and then must spend five months under house arrest.
Her company announced that Stewart would host a daytime talk show after her sentence.
Since her conviction, her company's share price has nearly tripled increasing her personal stake.
