Although a U.N. team verified the withdrawal of all Syrian troops from Lebanon on April 26, the US and Lebanese opposition leaders insisted that Syrian intelligence agents remained in Lebanon.
The killing of a prominent anti-Syrian journalist aroused suspicions that Syria had a hit list targeting opposition leaders.
Syria rejected all accusations.
US President Bush issued a new warning to Syria to withdraw intelligence forces.
The U.N. was encouraged by talks with Syria on the Security Council call for Syria to end its involvement in Lebanon.
A U.N. verification team was sent to Lebanon by late June to investigate.
