Martha Stewart, founder of a multimillion-dollar publishing and home-decorating empire, will be serving a 5-month sentence for lying to federal investigators about her suspiciously timed stock sale.
In a web site letter, Stewart says she is adjusting to life behind bars.
Stewart is spending time figuring out innovative way to do microwave cooking among other activities.
She was touched by the outpouring of support she received from millions of people who visited her web site and urged fans to send donations to the American Cancer Society.
Stewart's lawyer has filed an appeal.
