Ukraine's October 31 presidential elections reduced the candidates from 24 to two, pro-Moscow Viktor Yanukovich and pro-west Viktor Yushchenko.
The November 21 runoff election results are being disputed.
Yushchenko is claiming Yanukovich's victory is the result of an illegal electoral commission decision and is demanding they be annulled.
While campaigning, Yushchenko was struck by a mysterious illness in September and spent most of the month in an Austrian hospital.
He and his supporters believe he was poisoned by political rivals.
Doctors are still examining blood and other samples to determine the cause.
They expect him to make a full recovery.
