Martha Stewart reported to the Alderson Federal Prison Camp, known as Camp Cupcake, in West Virginia on October 8 to begin serving a five-month sentence.
She began her sentence despite her pending appeal in order to sooner put her nightmare ordeal behind her and reclaim her good life.
Stewart arrived in good spirits and adjusted well.
Prison officials and fellow inmates have been nice.
She keeps busy performing chores, taking walks, exercising in the gym, reading, writing, watching television news, and creating innovative microwave recipes.
She's received thousands of letters from fans and has had visitors, including her daughter.
