Financial contributions for Asian Tsunami relief had exceeded $10 billion by Jan. 12, 2005.
Governmental contributions passed $8 billion while private gifts exceeded $2 billion.
The United Nations announced that it has secured aid commitments worth $717 million.
Governmental contributions were led by Japan with $74m.
and Germany at $68m.
The outstanding organizational contributor was World Vision Australia which had raised $15.3m through a telethon.
Individual contributors were led by a Canadian couple Kroum and Eva Pindoff who gave $4.1m through the Canadian Red Cross which will be matched by the Canadian government to total $8.2m.
