An investigation uncovered violations of instructions and errors in operating the mini-sub that contributed to the recent accident.
Prosecutors accused a naval officer of negligence for damaging Russia's own Venom rescue vehicle, thereby necessitating international assistance.
Newspapers criticized the navy for waiting over a day before revealing information about the accident.
There are conflicting reports about whether the sub was caught in cables or fishing nets.
The Russian navy is considering buying at least one Scorpio and possibly a newer model Panther rescue vehicle.
The head of the Russian navy was fired, probably in part because of the accident.
