Yushchenko was sworn in as President of Ukraine on Sunday 23 January.
In a third round of voting on 26 December, Yushchenko won 51.99% of the vote to Yanukovich's 44.20%.
The Supreme Court had annulled the results of the second round of voting because of election fraud.
That decision followed 17 days of massive popular protests called the "Orange Revolution" after Yushchenko's campaign color.
Doctors confirmed that Yushchenko had been deliberately poisoned with TCDD, the most lethal form of dioxin.
Blood tests revealed levels of dioxin "more than 1000 times" normal.
Yushchenko will need treatment for months if not years.
