Abramoff's extensive corruption schemes are the subject of a Senate probe and criminal investigations by the Department of Justice and Florida prosecutors.
Investigators are looking at congressmen, aides, government officials, and lobbyists, including Rep. John Doolittle, Stephen Griles, and Tony Rudy, and will follow the case wherever it leads.
Scanlon pled guilty to bribery and agreed to make restitution to tribes.
His help would be crucial to the Abramoff investigation.
Abramoff pled guilty to conspiracy, fraud, and tax evasion and agreed to cooperate with prosecutors.
Co-defendant Adam Kidan agreed to testify against Abramoff regarding fraud in a ship company purchase.
