Tsunami relief contributions continued to grow.
The UN made Bill Clinton special ambassador for tsunami relief.
China's Shanxi Province gave Thailand $180,000 in medical equipment and cash.
The Asian Development Bank pledged an additional $800 million to Indonesia.
Hong Kong donated $192,000.
Saudi Arabia sent five aircraft and $100 million.
Switzerland loaned three helicopters to the UN.
Tiger Woods gave $100,00, matched by the PGA.
Australian tennis player Lleyton Hewitt gave $45,000 from auctions of three of his rackets.
Hong Kong stars auctioned off clothes and personal items, with the proceeds going to tsunami relief.
