As of 20 July, the death toll stood at 56, with all victims identified.
Police had finished their investigations on site and moved one subway car from the underground tunnel to a police compound for further investigation.
The suspected bombers, all four of whom were killed in the explosions, were Islamic extremists.
British of Pakistani origin, the four were captured on closed ciruit TV at King's Cross soon before the bomings.
An additional suspect was said to have been arrested in Cairo, Egypt, on 15 July.
