The July 7 London bombing death toll is now 56, including four suicide bombers.
Police identified the four and know details of their final movements.
All were British of Pakistani origin.
Police raided five premises in Leeds and recovered a car they expect will yield evidence.
Authorities were tipped off when one bomber's mother called a help line to report him missing.
ABC News reported that the alleged bomb maker behind the London attacks was arrested in Egypt.
Authorities fear that a number of recent arson attacks on mosques in England may have been retaliation for the bombings.
