Four coordinated bombs exploded in central London during morning rush hour on July 7th, coinciding with the G8 summit in Scotland.
About 700 were injured and 52 killed.
Three bombs were on subway trains and one on a bus.
Each was small enough to fit in a rucksack.
The Secret al-Qaida Jihad Organization in Europe claimed responsibility, to avenge British involvement in wars in Afghanistan and Iraq.
No evidence arose of suicide bombers.
Investigators viewed video by cameras on streets and subway platforms around London.
Londoners took the terrorist attacks in stride, used to IRA bombs and the WWII blitz.
