To combat childhood obesity in the US, schools are removing unhealthy food from vending machines, reducing the fat in lunches, and requiring more physical education.
New Hampshire is instituting twice-yearly weigh-ins for students.
Children's hospitals have weight management programs and a YMCA has a kid-friendly fitness room.
Efforts are being made to regulate advertising to young children.
Manufacturers offer cereals low in sugar and salt with more vitamins and whole grains.
US Cabinet secretaries and children's television networks are promoting healthier lifestyles for children.
In New Zealand, schools added a mandatory extra hour of physical activity for students every week.
