Abramoff pleaded guilty to conspiracy, fraud and tax evasion and agreed to cooperate with federal officials investing political corruption.
Abramoff is also facing trial on fraud charges in Florida connected with purchasing a casino cruise chip company.
In his plea agreement, Abramoff committed to making 25 million in restitution to his victims and paying 1.2 million to the IRS for tax evasion.
His prison sentence could be lowered depending on assistance he provides in the corruption investigation of as many as 20 members of Congress or top congressional aides.
