As of 29 September, Katrina's death toll had reached 1121 including 885 in Louisiana and 200 in Mississippi.
The economic impact was massive.
The global insurance industry was predicting costs of $40-$50 billion.
Agricultural losses were estimated at $900 million.
Louisiana's unemployment rate soared to 11.5%.
And U.S. industrial output rose only slightly because of cuts in the production of petroleum and chemicals in the Gulf region.
118 countries sent aid, including $2.5 million from Turkey.
The U.S. Congress was expected to approve tax breaks of $6.1 billion for people and businesses.
