An international group is studying an aromatose inhibitor, which may replace tamoxifin.
And a Taiwanese-U.S.
cooperative effort is developing a new breast-cancer drug.
NIH has undertaken a study of sisters to find genetic and environmental causes of the disease.
Other studies are looking into the effects and effectiveness of oral contraceptives, an underactive thyroid, olive oil, a cell's ability to repair DNA, and the flushing of milk ducts.
A new Dutch diagnostic tool could help some breast-cancer patients avoid unnecessary treatment.
And advances in technology and techniques have now made radiation safe for breast-cancer patients.
