The death toll from Hurricane Katrina surpassed 1,100.
Turkey has allocated 2.5 million dollars for victims and the Bosnian Red Cross announced that is has started raising money for victims, as well.
The US House of Representatives approved tax breaks for victims.
The hurricane caused job losses in Louisiana sending its unemployment rate soaring to 11.5 percent.
Agricultural losses are expected to reach an estimated 900 million dollars and US industrial output has been depressed by Katrina with severe cut backs in production of petroleum and chemicals.
