Following recovery of the submarine, Russian authorities praised the international rescue effort and thanked Britain, the U.S. and Japan, but questions were soon raised as to why their navy did not have the proper equipment for such an operation.
Updated equipment was soon purchased.
President Putin ordered an investigation of the accident.
On Sept. 4 Putin fired the head of the navy.
On Sept 6 the defense minister announced that the submarine accident was a result of outrageous violations of the instructions by senior officials of the Russian Pacific Fleet and that the crew had made errors.
