For three weeks plaintiffs in the Kitzmiller vs.
Dover Area School District trial presented expert witnesses who testified that intelligent design does not meet the definition of science because it cannot be proved or disproved.
For the next three weeks, the defense called witnesses who testified that intelligent design is not based on religious beliefs, but on observable, physical evidence from nature.
The judge ruled that compelling teachers to present intelligent design as an alternative explanation to evolution violates the Constitution.
Dover residents ousted all eight school board members running for re-election who put their town in the global spotlight.
