The District of Columbia, NY state, New Jersey, Connecticut and Chicago ban the use of hand-held cell phones while driving.
Some states or cities ban use with learner's permits, by school bus drivers, by minors for six months after getting their licenses, or require hands-free phones.
Every state has considered restrictions but bills seldom pass.
Some states, including Florida, prohibit local governments from restricting cell phone use.
Hands-free and hand-held cell phones are equally distracting.
Laws are often ignored.
Enforcement is spotty.
Hand-held phone use while driving is banned in 45 countries, including Australia, Germany, France, Britain and Japan.
