FARC rejected a government proposal to hold talks aimed at exchanging rebels for hostages held by the guerillas.
FARC asked the president to grant them the two southern demilitarized zones, before discussions could take place.
The government denied their request because it has to guarantee the safety of the people across the country.
The United Nations urged hostage release.
The rebel groups released 12 hostages.
The Columbian government plans to pardon more than 30 members of FARC as they negotiate a prisoner swap.
