Charles Taylor fled Liberia in August 2003 accepting an invitation from Nigeria for exile.
He lived in a luxury villa near the town of Calibar near the border with Cameroon.
He was accused of continuing to meddle in Liberian politics, of funding and planning the assassination of the President of Guinea and of backing Sierra Leone rebels.
He was also said to give support to Al-Qaeda in its efforts to destabilize West Africa.
In March 2006, Nigeria offered to return Taylor to Liberia for trial, but Liberia didn't want him so he remained in his luxury villa.
