The Dover, Pennsylvania school board passed a resolution in October 2004 requiring 9th grade biology students be told that evolution is a theory, not a fact, and that intelligent design is an alternative explanation of the origin of life.
The board is being sued by 11 parents of students who charge it is trying to promote a religion in violation of the US Constitution.
The school board argues it is informing students about differences of opinion, not endorsing any religious view.
The trial is underway.
