The Indian Space Research Organization (ISRO) and France will cooperate on a satellite to track tropical atmospheric conditions.
ISRO has short-listed experiments from five nations (US, UK, Sweden, Bulgaria, Germany) for a slot on India's unmanned moon mission, Chandrayaan-1, which is to map the lunar surface.
India can send a man into space within seven years.
Its first astronaut flew on the Soviet Salyut 7 in 1984.
Another died in the Columbia shuttle disaster.
India plans a telemedicine system to connect hospitals and patients via satellite.
India plans flight-testing of its cryogenic rocket.
It sought black-market electrical components for rockets.
