At the trial, a biochemistry professor at Lehigh and lawyers at the Thomas More Law Center testified for teaching intelligent design as a credible scientific theory.
Scientists testifying for the parents dismissed intelligent design because it can't be tested by experiment.
A federal judge ruled that teaching intelligent design as an alternative explanation to evolution violates the constitution.
He wrote that the overwhelming evidence established that intelligent design is a religious view and not a scientific theory and its inclusion in public schools violates the separation of church and state.
