The District of Columbia, New York and New Jersey passed legislation that bans using hand-held cell phones while driving.
More than 400,000 tickets and warnings have been issued since New York first enacted this law.
New Mexico and Chicago City only allow hands-free cell phone.
Texas is considering cell phone laws.
An Insurance Institute of Highway Safety survey said using any cell phones while driving is dangerous.
Drivers using cell phones are four times as likely to end up in a crash as drivers who didn't use a cell phone.
