The Indian Prime Minister has criticized economic sanctions imposed after the 1998 nuclear weapons tests, but noted that these have not hindered India's scientific progress.
India launched one rocket carrying two satellites, one for more detailed mapping, the other for home radio operators.
Its first unmanned moon mission, scheduled for 2007-2008, will carry three European payloads and perhaps one U.S. payload.
Meanwhile India is working with Russia to develop a satellite to enable youths in the two countries to communicate.
It will host twin international conferences on planetary exploration and space law for about 225 delegates in June.
