On the night of March 27, 2006 Charles Taylor vanished.
His spiritual advisor said he was hiding somewhere in West Africa.
On March 29 Taylor was arrested while attempting to cross over into Cameroon.
He was detained under armed guard and then placed on a presidential jet bound for Liberia.
He left Monrovia, Liberia an hour after arrival on a UN helicopter to Freetown, Sierra Leone where he was delivered to the UN-backed Special Court for Sierra Leone.
He was due to make his first court appearance on April 3 at 3 p.m.
