The US Virgin Islands now bans hand-held cell phone use while driving.
Eleven states including Colorado, Delaware, Maryland and Tennessee ban cell phone use by young drivers.
California prohibits phone use while driving by bus drivers but not others.
Under a Pentagon directive, bans on cell phone use while driving are becoming common on military bases.
In 2005, 38 states tried to pass restrictive legislation.
Effectiveness is difficult to assess because drivers or witnesses must confirm cell phone use coincided with accidents.
Enforcement is difficult because officers can't easily ascertain drivers' ages or if they are using hands-free phones.
