Barak Obama, who was a relatively obscure Senate hopeful just a few months ago, soundly defeated his opponent to become the third African-American US Senator in history.
The charismatic Obama catapulted to prominence after giving an electrifying keynote speech at the Democratic National Convention in July.
In the following weeks, he came to have such star power that he was recruited to stump for Democratic presidential nominee John Kerry and fellow congressional candidates.
He draws the support of voters from all racial and economic groups.
Obama is widely touted for a future leadership position in his party.
