Former Liberian President Charles Taylor fled to Nigeria in August 2003 and is under house arrest at a riverside villa in Calabar.
Taylor regularly defies restrictions against travel, political activity or media contact.
He is actively trying to destabilize West Africa, spending money he looted from Liberia.
Taylor meddles in Liberian affairs, harbors members of Al-Qaeda, and ordered an assassination attempt against Guinea's President Conte.
Nigerian President Obasanjo agreed to turn Taylor over to Liberia but is pressured to send him to war crimes court in Sierra Leone where Taylor is under indictment for crimes against humanity while backing rebels.
