Colombian President Pastrana held talks with FARC and designated a safe haven until FARC hijacked an airliner and kidnapped a senator.
In 2003 FARC bombed American-frequented pubs and abducted three Americans after a plane crash.
In 2004 FARC killed five members of a Colombian family and bombed a peasant home, killing one.
The US designated FARC a terrorist organization and aided Colombia financially in its anti-FARC war.
President Uribe offered to swap 50 jailed rebels for 50 hostages.
FARC-government fighting kills 3,500 yearly.
A FARC bomb narrowly missed Uribe in 2002.
Uribe is pursuing an aggressive military offensive against FARC.
