Barack Obama, a black state senator in Illinois, first came to national attention with his electrifying keynote speech to the Democratic National Convention in July 2004.
He went on to win overwhelmingly in the race for U.S. Senator.
He was outstanding for his inclusive rhetoric, ability to attract support of liberals and white middle-class voters, and his fund raising for his own and other Democratic candidates.
While running his own campaign he stumped for other candidates in more than a dozen states.
In November 2004 Barack Obama was already being touted as a future presidential candidate.
