Taylor vanished two days after President Obasanjo said Liberia could take Taylor into custody.
Nigerian police arrested Taylor a day after his escape, as he tried to cross into Cameroon with sacksful of dollars and euros.
He was detained under armed guard in a military camp before being put in handcuffs on a presidential jet Wednesday bound for Liberia.
An hour after arrival he left for Sierra Leone aboard a UN helicopter.
He was to make his first court appearance on Monday, April 3, 2006, the first African head of state to face an international war crimes tribunal.
