On June 16, 2005 Rep. Randall "Duke" Cunningham insisted there was nothing wrong with his living on a yacht owned by the executive of MZM, Inc. for which he had helped gain government contracts or selling a San Diego home for $1,675,000 to the executive who resold it for $975,000.
On July 1 federal agents raided Cunningham's San Diego residence and the MZM offices and yacht in Washington.
Cunningham soon announced that he would not seek reelection and the executive stepped down.
On August 13 Cunningham asked donors for permission to use their campaign contributions for legal expenses.
