Nigeria is using bamboo to revitalize its agriculture.
It has set up a database exploring its abundant bamboo resource to produce byproducts.
A state in northeast India plans to set up power stations that run on bamboo to help meet the regions energy needs.
A Chinese company has successfully produced fiber from maize and blended it with bamboo fiber to make environment-friendly clothes.
Forestry experts in northwest China have identified more than 20 insects, which are causing arrow bamboo to wither and die causing shortages of food for pandas.
Help for pandas is being arranged.
