Barak Obama was received like a rock star and hero at a luncheon where he was bestowed the Harvard Law School Association Award.
Obama took a 10-day tour of the Middle East that included visits to Iraq, Kuwait, Jordan, Palestinian territories, and Israel.
He met with Israeli Foreign Minister Shalom and conveyed to him the United States' support for Israel as its leader Ariel Sharon lay stricken by a stroke.
Obama won a Grammy Award for his readings of his autobiographical book Dreams From My Father, which became a best seller as he became a rising political star.
