The Columbian Navy captured a member of the rebel group, Revolutionary Armed Forces of Columbia (FARC), who was believed to be involved in slaughtering five members of the same family.
US warned US citizens in Columbia of a possible spike in "terrorist activity".
FARC, with about 17,000 fighters and a smaller leftist guerilla group are locked in a 40-year civil war with the government.
FARC allegedly finances itself through drug trafficking and kidnappings.
About 3,500 people are killed yearly.
Columbia's president is ready to negotiate a prisoner swap with FARC.
