Under pressure from Congress, Major League Baseball's players association toughened drug testing rules and penalties again for the 2006 season.
Suspensions will be increased to 50 games for a first offense, 100 for a second, and a lifetime ban for the third.
Congress launched an undercover probe into illegal steroid use in Major League Baseball.
News of the probe surprised MLB officials.
Rafael Palmeiro was suspended 10 days for a positive steroid test.
He denied intentionally taking the drug.
Other players with 10-day steroid test suspensions were Felix Heredia and Carlos Almanzar.
New doping allegations surfaced about Barry Bonds.
