India's space program is developing on several fronts.
India is planning an unmanned moon mission to map the moon's surface and produce a chemical map of the moon.
Experiments from five countries (the U.S. and four European nations) are short-listed for this satellite.
It has an agreement with France to launch a satelite perhaps in 2008 to make climate predictions more accurate.
It will set up a telemedicine system, linking doctors at the best hospitals with patients across India.
Afghanistan has asked India for help setting up a similar program in Afghanistan using Indian satellites.
