Major League Baseball players who have admitted to using steroids include Ken Caminiti, Mark McGwire and Jose Conseco.
Players suspected of steroid use include Barry Bonds, Sammy Sosa, Jason Giambi, Rafael Palmeiro, Ivan Rodriguez and Juan Gonzalez.
MLB's recently toughened penalties of fines from $10,000 to $100,000 and suspensions from 10 days to one year are far below international anti-doping standards.
US lawmakers passed the Anabolic Steroid Control Act which added steroid precursors to the list of controlled substances.
In their investigation of steroid use in Major League Baseball, lawmakers found the penalties for positive steroid tests inadequate.
