Wichita police arrested the BTK strangler during a traffic stop on February 25.
Dennis Rader, serial killer of at least 10, sent numerous taunting messages and clues in the 1970's before going silent in 1979.
In March 2004, he mailed evidence of a previously unattributed 1986 murder to the Wichita Eagle.
More letters, clues and evidence followed.
Thousands of tips poured in and police received help from forensics experts.
Police long believed BTK graduated from Wichita State University, as Rader had.
DNA evidence helped solve the case.
Police learned of the last two BTK victims upon his arrest.
