Rep. Randy Cunningham resigned from Congress after pleading guilty to taking at least $2.4 million in bribes to help friends and contributors win federal defense contracts.
The FBI is still conducting its investigation of defense contractors and others tied to Cunningham.
He kept a "bribe menu" on congressional stationary indicating how much he demanded in exchange for federal contracts.
A federal judge sentenced Cunningham to eight years and four months in prison.
Cunningham was also ordered to pay $1.8 million in restitution.
