During his first 15 months as a U.S. Senator (Jan 2005-Mar 2006), Obama became better known and more widely admired.
His book "Dreams From My Father" became a bestseller.
On the senate floor he demonstrated willingness to work on a bipartisan basis on foreign and domestic issues.
In party affairs he continued his successes as a fundraiser.
One political analyst said, "The party needs him and for all I know, the nation needs him".
Some compared him to John F. Kennedy but Doris Kearns Goodwin warned there were also similarities to William J. Bryan.
