India's space program began in 1972.
It aspires to be a major space power.
India developed a unique universal launching pad and plans a sophisticated propellant plant for its launch vehicle, delayed by sanctions following India's 1998 nuclear testing.
India has launched eleven remote-sensing satellites and two satellites in one mission.
Communication satellites include Hamsat for Ham radio and distance-learning Edusat.
India and Russia plan a youth communication satellite.
In 2005 ISRO hosted international conferences on planetary exploration and space law.
Europe's Ariane program problems delayed launch of India's telecast and communication satellite INSAT-4A.
Boeing withdrew from Indian satellite cooperation.
