Bamboo has many uses.
In the home, it is used for flooring, kitchen cabinets, counter tops, and chairs.
India is allowing its islands that were struck by the tsunami, to build makeshift houses from bamboo and other woods, which can withstand quakes.
Ethiopia hopes to optimize ways of producing bamboo to reduce poverty.
Large areas of arrow bamboo provide food for giant pandas in northwest China.
Now they are suffering from hunger because large tracts of arrow bamboo died.
It takes 10-15 years for new plants to grow.
