In 2005, 38 states tried to pass legislation restricting cell phones while driving.
Bills were passed or are still being considered in 22 states.
The National Transportation Safety Board is urging states to restrict young drivers because teens account for a large share of traffic fatalities and cell phone use increases the problem.
However, enforcing laws for young drivers is difficult.
Both the U.S. Virgin Islands and Lackland Air Force Base have cell phone laws in place.
