Rader confessed to six killings on the day of his arrest, but police revealed little detail.
There was much public speculation and some media reports of possible links between Rader and BTK including talk of a computer disc and DNA evidence, but investigators remained tight-lipped.
On March 1 Rader was charged with 10 murders with bail set at $10 million.
On April 19 Rader waived his right to a preliminary hearing at which the prosecution would explain how the police had tied Rader to the killings.
This, as the DA said, "prolongs the agony of the public to know."
