In November, Colombian police arrested a FARC assassin, the army killed a FARC leader, and the court approved the extradition of a FARC chief to the US to face narcotics trafficking and money laundering charges.
FARC rebels murdered four indigenous Indian leaders in less than a week.
The government and FARC continued to argue over details of a prisoner swap.
The UN urged Colombia to speed up negotiations for hostage release.
December 2, the government announced it would pardon 23 FARC members to facilitate reaching a humanitarian accord with FARC.
Colombian police may have kidnapped a FARC rebel in Venezuela.
