The FARC, Colombia's largest leftist guerrilla force, commits selective murders, slaughters and other terrorist acts.
In 2003, FARC commandos attacked two Bogota pubs, targeting US citizens who frequented them.
FARC kidnaps hundreds of people a year for ransom and holds dozens as exchangeables, including Colombian politicians, police officers, soldiers and currently three US citizens.
Colombia's government is willing to negotiate a prisoner swap with FARC to free rebel hostages, including the three Americans.
The move is encouraged by the UN.
So far FARC has not agreed to the government's terms.
FARC has ordered its troops to kill Colombia's president.
