Pennsylvania's Dover School Board voted requiring teachers to read a brief statement about intelligent design to students before teaching classes on evolution.
Intelligent design implies that nature is so complex it must be the work of a single creator rather than evolution.
The school board stated that intelligent design provides an alternative to teaching evolution and denies that it is "religion in disguise".
Dover parents brought suit against the school board charging that teaching "intelligent design" is a clear violation of the principle of separation of church and state.
