Police arrested Dennis Rader on Feb. 25, 2005 and identified him as the serial killer BTK accused of 10 killings 1974-91.
BTK had taunted police with letters to them and the media, but efforts to find him failed and in 1979 the letters ceased.
They resumed in March 2004 and the investigation of the BTK case reopened.
Forensic experts studied DNA swabs that Kansas Governor Sibelius says linked Rader (BTK) to his victims.
Little else has been revealed as to how the perpetrator of these crimes was identified and tracked down.
