At a sold-out luncheon for black alumni at Harvard Law School, Obama was introduced as a rock star and hero.
He urged the nearly 1,000 attendees to take personal responsibility in combating urban poverty.
In 2005 Obama called for troop reduction in Iraq and a timeframe for phased withdrawal.
He visited Israel and met with the Prime Minister and mended a rift with John McCain over lobbying reform.
He won the Best Spoken Word Grammy for his autobiographical "Dreams From My Father".
He became an important fundraiser for fellow democrats and tweaked the press for its fawning coverage of him.
