The FBI and other federal agencies are investigating Rep. Randall "Duke" Cunningham for selling his house in November 2003 to a military contractor, Mitchell Wade, for an inflated price.
Agencies are probing Wade's efforts to repay Cunningham for his support in gaining federal contracts.
Cunningham was living on Wade's yacht, which has also raised questions about improper financial links.
He defended his boat arrangement as proper saying that he paid fees and services in lieu of rent.
Cunningham is asking his contributors, including Wade, for permission to use their campaign donations for his legal defense.
