Congressional investigators chided Major League Baseball leaders for being uncooperative regarding steroid use and urged star players to take public responsibility for their actions.
Congress also launched an undercover probe.
Players proposed strengthening the collective bargaining steroid proposal.
Bud Selig proposed a 50-game suspension for first offenders, 100-game suspension for second, and lifetime ban for third.
2003 tests showed 104 steroid users.
Eleven players were suspended for steroids in 2005.
Felix Heredia, Carlos Almanzar and Rafael Palmeiro tested positive.
BALCO's Victor Conte and James Valente, Bonds trainer Greg Anderson, and chemist Patrick Arnold were charged or sentenced concerning steroid distribution.
