Cunningham resigned from Congress on Nov. 28, 2005 after pleading guilty to taking at least $2.4 million in bribes to help four unnamed co-conspirators win defense contracts.
The FBI continued its investigation of defense contractors.
On Feb. 18 prosecutors recommended that Cunningham serve the maximum ten years in prison, pay $1.5 million in taxes and forfeit $1.85 million in bribe money and items provided by co-conspirators.
On March 5 he was sentenced to 8 years and 4 months in prison and ordered to pay $1.8 million in restitution.
