Major League Baseball players Ken Caminiti, Mark McGwire, and Jose Canseco admitted taking steroids.
Barry Bonds, Sammy Sosa, Jason Giambi, Rafael Palmeiro, Ivan Rodriguez, and Juan Gonzalez are accused or suspected of steroid use.
Caminiti claimed half the players used them.
5-7 percent of players tested positive in 2003 and 1-2 percent in 2005.
Baseball Commissioner Bud Selig investigated steroid use in 1998 and urged banning over-the-counter sales.
A pamphlet in English and Spanish on steroids' effects was distributed to players.
Drug tests for players began in 2004.
Some steroids became controlled substances.
Congress held hearings on baseball steroid use.
