Texas legislators will vote on a constitutional amendment banning same-sex marriage that is not expected to pass.
New Hampshire lawmakers defeated a constitutional ban on gay marriage.
The issue is under debate in courts in Maryland, California, New Jersey, New York and Washington State.
The US government does not recognize same-sex marriage.
Massachusetts is the only state to legalize it, although Vermont and Connecticut allow legalized civil unions.
Canada passed landmark legislation to legalize gay marriage everywhere in the country.
However, gay marriage is not legal in Sweden and Taiwan.
Many countries have legalized civil unions, but not gay marriage.
