Russia's Gazprom will control the Northern European Gas Pipeline, bringing Siberian gas directly to Europe.
It will bypass Poland, Ukraine and Belarus, who fear being cut off from Russian gas.
Gazprom and Germany's BASF will build it.
Gerhard Schroeder, criticized for profiting from a project he supported while German chancellor, will chair the board.
Gazprom arranged a monopoly on gas from Turkmenistan and Uzbekistan through Kazakhstan.
The Austria-Bulgaria "Nabucco" project is a gas pipeline from Turkey to Austria.
A Southern Europe Gas Ring from Turkey through Greece and across the Ionian Sea to Italy is to be completed by 2006.
