The blackout in August 2003 that struck the northeastern U.S. and parts of Canada was primarily caused by the deregulation of the utility companies.
Experts said that changes in the industry had several adverse effects, including loss of experienced personnel and lawyers and MBAs now heading these competitive companies rather than engineers.
Power plant capacity and its state of repair are proprietary now and not available to system operators who manage regional power grids.
The energy law provides for mandatory reliability rules, but no power to enforce rules.
