Parliamentary elections were held in Kyrgyzstan on 27 February, with presidential elections planned for October.
Akayev supporters won a landslide victory in most areas, but both opposition leaders and western observers cited mass violations.
Run-off parliamentary elections were held in many regions on 13 March.
The opposition was defeated but refused to accept the results and demanded Akayev's resignation.
Even before the election, opposition leaders had been calling for Akayev to step down as President at the end of October in accordance with the constitution.
But Akayev refused to resign or to annul the election results.
