Prominent Turkish novelist, Orhan Pamuk, was indicted over controversial remarks about the Armenian massacres.
Pamuk is charged under Turkey's penal code which carries a jail term of more than three years for a person who "explicitly insults" the Turkish republic.
The European Union (EU) warned Turkey that its prosecution of Pamuk could damage its chance of joining the EU and is a test of Turkey's commitment to freedom of expression and reforms in its law.
European countries, U.S. and activist organizations have criticized Turkey's lack of democratic principles and citizen's rights.
