A group of 169 Turkish intellectuals asked the government to scrap laws that limit freedom of expression and interfere with Turkey's democratic process.
Istanbul's court dropped charges against Pamuk stating that it wasn't legally competent to judge this case.
The court was chided for framing the dismissal in bureaucratic terms rather than addressing freedom of expression.
About 70 intellectuals have been charged as well, but they don't have the same high profile as Pamuk.
The EU pressed Turkey to address legal loopholes limiting freedom of speech in other cases.
