President Bush nominated his longtime lawyer and friend Harriet Miers for the U.S. Supreme Court to replace retiring Justice Sandra Day O'Conner.
Miers, currently White House counsel, would join Justice Ruth Bader Ginsburg as the second woman on the court.
Conservatives urged Mr. Bush to withdraw her nomination saying that she lacks the qualifications having never been a judge and has little experience in constitutional law.
They further state that her nomination looks like cronyism.
There is also concern that her religious belief may influence her decisions as a Justice.
