On June 29, 2005 the Canadian House of Commons passed legislation to legalize gay marriage on a national basis.
In Britain a Civil Partnership Act took effect on Dec. 5, 2005 granting some legal rights and tax benefits to gay couples.
By March 2006 homosexual rights advocates were demonstrating in favor of gay marriage in Taipei, Taiwan.
In the U.S. a Maryland judge threw out a law banning gay marriage, lawmakers in New Hampshire defeated a proposed constitutional amendment banning gay marriage, and seven states were prepared to vote on such amendments in November.
