Special events were planned at bookstores worldwide, including Asia, for the much-anticipated release of Harry Potter and the Half-Blood Prince.
The author herself was to host a special celebration at Edinburgh Castle for 70 children from around the world.
A US drug store accidentally sold one copy of the book ahead of the release date.
The customer agreed to return the book.
The book shattered publishing records in the United States.
A Braille edition of the latest Harry Potter book is was released on July 19.
In October, French, Portuguese and Chinese editions of the book were released.
