An open-air requiem mass was held for Pope John Paul II in St. Peter's Square from 10am-12:30 pm on Friday.
As the mass ended, lengthy applause broke out from the enormous throng of mourners.
The body, in a plain cypress wooden coffin, was laid to rest in the crypt of St.Peter's Basilica following the funeral.
On Saturday a monument was unveiled at the Krakow cemetary where the pope's family is buried.
The cardinals will meet in secret to elect a successor.
