Homosexual marriages were legalized in Spain including the right to adopt.
Some European countries have passed legislation authorizing gay marriages, but not all give gay couples the right to adopt.
Poland's senate approved draft bill allowing same-sex partnerships.
In Canada, seven provinces authorized gay marriages.
In the U.S., gay marriages are banned in 18 states.
Massachusetts legalized gay marriages and Vermont's law applies to civil unions.
Judges in California and New York ruled state laws banning gay marriages were unconstitutional.
