Russia cut the flow of natural gas through the Ukrainian pipeline in early January because of a pricing dispute.
The resulting European energy crisis made European governments question Russia's reliability and seek alternative sources.
Austria is weighing the construction of a pipeline from Iran through Turkey and the Balkans.
Croatia and Hungary are considering a pipeline to bring liquid gas from North Africa and the Middle East.
The U.S.supports a proposed pipeline under the Caspian Sea to bring gas from Turkmenistan and Kazakhstan through Azerbaijan, Georgia, and Turkey.
Pipeline explosions cut Russia's gas supply to Georgia and Armenia.
