Biologists question evidence in sightings of rare ivory-billed woodpecker.
The issue is whether four seconds of fuzzy videotape is an ivory-billed or pileated woodpecker.
Recordings of the ivory-billed woodpecker's distinctive double-rap sounds convinced scientists of this bird's existence.
A crew from Cornell Lab and its partner agencies will train 100 volunteers for a six-month search of 500,000 acres in the eastern Arkansas wetlands.
An ivory-bill specialist criticized the finding saying the bird's existence hasn't been confirmed and the videotape shows a pileated woodpecker.
