Turkey was heavily criticized by international human rights groups over Orhan Pamuk's trial.
Turkish intellectuals and EU officials demanded that Turkey change the laws that limit freedom of expression.
To avoid an EU confrontation, Turkey's justice minister sent Pamuk's case back to the local Istanbul court, which then dropped the charges on a technicality.
The EU welcomed the ruling, which came just days before it was to begin a review of Turkey's justice system.
Turkey categorically denies Armenian accusations that up to 1.5 million died in a genocide orchestrated by the Ottoman Empire between 1915 and 1917.
