Kyrgyz oppositionists, fearing President Akayev might hold onto power longer than his constitutional two terms, rallied and urged him to step down.
He refused, saying elections were fair, opposition leaders were unnecessarily inciting civil war, and talks were the solution to the crisis.
The opposition refused to accept a landslide victory by Akayev supporters in parliamentary elections and claimed fraud.
They blocked roads, occupied government buildings, and took a governor and district chief hostage.
When police fired shots to dispel rioters, crowds beat four policemen to death.
Akayev ordered fraud claims investigated and replaced the interior minister and prosecutor-general.
