Prior to parliamentary elections on Feb. 27, 2005 about 300 opposition activists gathered in Kyrgyzstan's capital Bishkek demonstrating in favor of democratic elections and calling for President Askar Akayev to step down at the end of his second term in October.
The administration staged a counter-demonstration.
After Akayev won overwhelming election victories the opposition charged the government with mass election violations, blocked roads, occupied government buildings, and held a regional governor and a district chief hostage.
Akayev ordered investigation and negotiations and fired the interior minister and prosecutor general while police dispersed crowds in Bishkek.
