President Bush has nominated White House Counsel Harriet Miers to the Supreme Court.
The nomination must be confirmed by the U.S. Senate.
There is increasingly strong opposition to the nomination, with outrage expressed by conservatives such as Pat Buchanan and Charles Krauthammer.
The major objections are that she has few credentials or qualifications and that the nomination looks like cronyism.
Bush cited religion as one criterion for her selection.
She is scheduled to face the Senate Judiciary Committee in November.
The committee sent her a questionaire, but found her responses "inadequate" and "insulting" and asked her to redo it.
