The sixth novel in J.K.Rowling's Harry Potter series, "Harry Potter and the Half-Blood Prince," will go on sale at 12:01 a.m. on July 16.
Long before its release, the book was breaking all publication records.
The first U.S. printing was to be 10.8 million copies, with 635,000 copies of the audio book.
Amazon.com had more than 1.2 million pre-orders world-wide and bookstores expected to sell 50,000 copies an hour for the first 24 hours.
In early June, five warehouses were under tight security as they prepared the books for shipment.
