The world said a final farewell to Pope John Paul II at his solemn funeral on April 8.
A huge throng of mourners applauded as his coffin was carried from Saint Peter's Basilica and placed before the altar.
Dignitaries stood in respect.
The requiem mass followed centuries of solemn ritual.
He was interred in the crypt of Saint Peter's Basilica.
The late Pope's native Poland declared a national holiday.
Hundreds of thousands of mourners gathered to watch the televised funeral.
Hundreds gathered for interfaith prayers at a Warsaw synagogue.
Cardinals will meet on April 18 to elect a new pontiff.
