Faced with mounting criticism, Russia restored gas withheld from Ukraine in an alleged pricing dispute but suspected to be Moscow's meddling in Ukraine's internal politics.
Steady fuel supplies from Gazprom became questioned.
Austria proposed a gas pipeline from Iran to Austria as part of Nabucco.
Gas pipeline explosions in January 2006 were blamed on both Moscow and terrorists.
Croatia and Hungary are considering a liquified petroleum gas terminal on the Adriatic coast and a pipeline to Europe to decrease reliance on Russian gas.
A US-backed trans-Caspian pipeline is proposed that would bring Central Asian gas to Europe and bypass Russia.
