California imposed rolling power cuts in 2001 to deal with strains on the grid.
In 2005 Los Angeles suffered three significant electrical failures, due to mistakes by workers or automatic systems.
In 2005 the US and Canada discussed deregulation of the electric system, widely considered to be a cause of the 2003 blackout.
Utilities now have little incentive to invest in transmission lines, keep reserve power to minimize shortages, or share information on power plant operating status.
Plants operate closer to reliability limits more often.
MBAs and lawyers head power companies rather than engineers.
Energy company ownership continues to consolidate.
