Massive uprisings continued in Kyrgyzstan, fueled by anger over the rigged parliamentary elections.
When protesters finally stormed the presidential compound on 30 March, President Akayev fled to Moscow.
Two nights of looting and gunfire followed in Bishkek.
A delegation headed by the new speaker of Parliament went to Moscow to negotiate with Akayev.
Akayev signed his formal resignation at the Kyrgyz Embassy in Moscow on 4 April.
His recorded statement was to be shown to Parliament and then broadcast on national television.
Presidential elections are now scheduled for 26 June.
