The funeral ceremony for Pope Paul II began in Saint Peter's Square in front of a huge throng of mourners including state leaders who applauded as the coffin was placed on the altar.
In Tokyo, Japan, diplomats and government officials joined 1,500 Catholics in a mass mourning for the pope.
Several hundred people of all faiths prayed at a Warsaw synagogue.
The Grand Rabbi of Poland led the ecumenical prayer.
A monument to Pope Paul II was inaugurated in a Krakow cemetery, where the late pope's family is buried.
