The ivory-billed woodpecker, a bird long thought extinct, has been sighted in the swamp forests of eastern Arkansas for the first time in more than 60 years.
The bird disappeared after large-scale logging felled thousands of acres of forest.
In February 2004, a sighting was thought to be the ivory-billed woodpecker.
There have been 15 sightings captured on video although researchers can't determine how many were seen.
The government proposed $10 million for efforts to protect the bird.
Private groups will contribute another $10 million.
