Security experts warned that terrorists could unleash electromagnetic bombs that can be catastrophic.
The U.S. is particularly vulnerable because it relies heavily on telecommunications and electronics.
Homeland Security is being urged to set up mechanisms to stop attacks and restore power.
Electric company officials have been warned that they need to focus more on cyber-security to prevent hackers from attacking U.S. electric power grids.
Many nuclear power plants in the U.S. lack sirens warning of a nuclear emergency if electricity also was blacked out.
