By April 2005 the cause of legalizing gay marriage was making remarkable headway in Europe and Canada, edging slowly ahead in sections of the U.S. and facing aggressive opposition in some other states.
Spain, Denmark, Norway, Sweden, Iceland and Finland had legalized the practice.
In Canada 7 of the 10 provinces and one of three territories accepted gay marriage.
In the U. S. eighteen states had passed constitutional amendments prohibiting it while Massachusetts allows and three New England states, New Jersey, California and Hawaii had taken steps toward allowing it.
