The ivory-billed woodpecker, thought for 60 years to be extinct, has been discovered in a remote Arkansas swamp.
Its existence has been confirmed by at least 8 sightings, a 4-second video, and its distinctive "double-knock" drumming.
The first sighting was in February 2004 but was kept secret for over a year while experts confirmed the discovery and protected the bird's territory.
Private groups and individuals have raised $10 million for protection of the woodpecker and its environment, while the federal government has proposed $10 million in federal funds.
Massive logging had destroyed the woodpecker's habitat.
