Spain joined Belgium and the Netherlands as the only European countries to legalize homosexual marriages.
In the US, a judge threw out an amendment to the Louisiana Constitution banning gay marriage.
Massachusetts legalized gay marriage in May.
Arkansas, Georgia, Kentucky, Michigan, Mississippi, Missouri, Montana, North Dakota, Ohio, Oklahoma, Oregon and Utah have all passed constitutional bans on gay marriage.
A US judge ruled that California state law effectively bans gay marriage as unconstitutional.
Over half of Canada's 10 provinces and tree territories allow same-sex marriage.
