The rediscovery of the ivory-billed woodpecker was challenged in late April, almost three months after its announcement.
Three biologists planned to publish a paper saying that the evidence was insufficient, a conclusion also reached by Sibley, author of well-known field guides.
But two of the scientists were given recordings based on 18,000 hours of audio and, on the basis of this "new evidence," they withdrew their challenge and the paper was not published.
In January 2006, however, the third biologist voiced the strongest criticism to date, saying that he was still not convinced.
The search continues.
