Turkey's Justice Ministry declined to rule on whether Pamuk should be tried, citing recent penal code amendments.
It sent the case back to the Istanbul court, which dropped the charges against Pamuk.
The case divided Turkey and embarrassed its liberals.
Pamuk's remarks also highlighted another painful episode in Turkish history, the 30,000 Kurdish deaths in recent guerrilla fighting in Turkey's Kurdish southeast.
Turkish intellectuals, the EU, and most of the West called on Turkey's government to scrap laws limiting freedom of expression.
Potential EU partners wanted to know that Turkish laws were the same as laws elsewhere in the EU.
