Following Pope John Paul II's death on April 2, mourners gathered worldwide.
Chinese Catholic Bishops sent condolences to the Vatican.
Philippine Catholics express deep grief as church bells tolled.
Over 500,000 people signed an online condolence book.
On April 3, the late Pope's body lay in state in the Vatican's Apostolic Palace.
Hundreds of thousands of pilgrims arrived from Europe and around the world to pay their respects.
Some 800,000 gathered in Krakow, Poland for a memorial mass.
Hundreds of dignitaries, leaders and heads of state from around the world headed to Rome for the funeral.
