Opposition against Akayev strengthened with international criticism for election abuses, his government's crackdown on opposition groups and independent media, and his failure to bring those responsible for killing six peaceful demonstrators in 2002 to justice.
Poverty and widespread corruption contributed to public anger.
Akayev fled to Russia after opposition supporters stormed the main government building and mobs looted parts of Bishkek.
He resigned as president in Moscow, with impeachment the alternative.
In his address to the nation, Akayev apologized to people who bore him grudges, hoped the presidential election would be democratic, and said he wouldn't fight the new government.
