On March 24, 2005 mass protests outside the presidential compound in Bishkek turned violent.
Demonstrators broke into the building and beat several officials severely.
Akayev fled the country for Russia and soon announced in Moscow that he would resign if the Kyrgyzstan government would guarantee his safety.
On April 3 a Kyrgyzstan parliamentary delegation arrived in Moscow and after 3 hours of talks Akayev signed a resignation document.
He also taped an 18-minute farewell address to be played in Bishkek while he remained in Moscow.
New presidential elections are scheduled for June 26.
