On Oct. 27, 2005, a little more than three weeks after offering the nomination of Harriet Miers, President Bush announced that she had withdrawn her nomination.
Many expressed sympathy for how she had been treated.
Republicans, including Miers herself, blamed failure of the nomination on the Senate Judiciary Committee's demands for documents from the White House, but the committee chair denied intruding on executive privilege.
Democrats blamed the failure on right-wing ideologues.
Sen. Lott (R-MS) blamed it on a nomination based on cronyism.
On Oct. 28 President Bush said he would quickly select another candidate.
