President Bush's nomination of Harriet Miers for the Supreme Court caused much consternation.
The White House counsel was endorsed by the Democratic Senate leader while the Republican conservative base was splintered.
Moderate Republicans sided with their president while most Democrats and liberal advocacy groups stayed out of the fray.
On Oct. 12, 2005 Bush tried to promote confirmation by vouching for Miers as an evangelical Christian, but conservatives said the issue was not religion but her lack of qualifications.
On Oct. 21 the Senate Judiciary Committee found Miers' answers to a committee questionnaire "inadequate," "insufficient," and "insulting."
