Orhan Pamuk went to court on 16 December for outspoken comments made during a Swiss newspaper interview about the Armenian massacres.
The EU warned that the trial could affect Turkey's EU accession process because it would indicate the strength of Turkey's commitment to recent reforms guaranteeing freedom of expression.
The EU Enlargement Commissioner said, "It is not Orhan Pamuk who will stand trial, but Turkey".
The trial was suspended until 7 February pending a decision from the Justice Ministry.
The offense had been made before the new penal code had gone into effect and therefore came under the old law.
