Prominent award-winning Turkish novelist Orhan Pamuk was indicted for insulting the Turkish identity by comments he made to a Swiss reporter about one million Armenians massacred in Turkey during World War I. He could face up to three years in prison.
The US and EU called on Turkey to drop the charges.
His December 16 trial was suspended until February 7 because the court lacked a justice ministry order to proceed.
The case has stirred outrage across Europe.
EU officials were there to observe the trial, the outcome of which could damage the Turkey's chances of joining the EU.
