Harriet Miers withdrew her nomination from consideration as a Supreme Court justice.
Members of the Senate Judiciary Committee questioned her conservative credentials, lack of judicial experience and criticized her for not completely answering a questionnaire about her work at the White House.
Others said the White House bungled the nomination from the start.
Many agreed that although she is a very capable person, President Bush shouldn't have chosen someone not qualified to serve on the Supreme Court.
