Harriet Miers withdrew her nomination to the Supreme Court three and a half weeks after its initial announcement.
Bush declared on 27 October that his choice had withdrawn her name and that he had "reluctantly accepted" her decision.
She claimed that the fight over her nomination would be a burden for the White House.
She also said that she wanted to protect the independence of the executive branch, citing the battle over access to her White House legal writings.
She will continue to serve as White House counsel.
Bush promised to name a replacement "in a timely manner."
