Pope John Paul II died on Saturday night, 2 April, after a long battle with Parkinson's disease.
He had had acute breathing problems for two months and had suffered a heart attack two days before his death.
His body was displayed at the Vatican's Apostolic Palace on Sunday.
The funeral is to be held on Friday.
Two hundred world leaders are expected to attend, creating an enormous security problem.
Meanwhile more than a million pilgrims have been gathering to pay their respects.
His remains are to be interred in the crypt of St. Peter's Basilica.
