Canada passed legislation authorizing gay marriages and granting same-sex couples legal rights equal to those in traditional unions.
In Sweden, civil unions between homosexuals are legal and the government will decide if the law should be changed to include marriage.
Under the Civil Partnership Act passed in Britain, homosexual couples will have the same rights as heterosexual couples.
Texas legislation to amend the constitution to ban same-sex marriages is being discussed.
Homosexual rights activists urged the Taiwan government to grant homosexual couples the right to marry.
