The case against Orhan Pamuk ended on 23 January.
The Justice Ministry had refused to issue an approval of the prosecution and told the Istanbul court that it should determine whether to proceed.
The Istanbul court dropped the charges.
Pamuk's lawyer criticized the decision, saying that it was framed in bureaucratic terms and avoided the issue of freedom of expression.
Turkish nationalists were outraged.
The EU Enlargement Commissioner said that Pamuk was not the only one facing such charges, he was "just the most high-profile case".
PEN says that some 70 Turkish intellectuals have been charged with similar offenses.
