The Northern European Gas Pipeline, which will bring gas from Northern Siberia through Russia and under the Baltic Sea to northern Germany, then to the Netherlands and under the English Channel to Britain.
Poland, the Baltic states, Belarus, and Ukraine are critical of the pipeline, because it bypasses current transit routes through those countries.
The Southern Europe Gas Ring project is to transport natural gas from the Caspian Sea area and Central Asia through Turkey and Greece then under the Ionian Sea to Italy.
Construction of the Turkey-Greece segment is scheduled to start in July 2005.
