Pope Paul II died after a long battle with Parkinson's disease.
The Pope's body was displayed at the Vatican's Apostolic Palace and on Vatican television and will be interred in the crypt of Saint Peter's Basilica.
A vast security operation went into effect as dignitaries and over a million pilgrims from around the world arrived paying their last respects.
Near Krakow, Poland, 800,000 people gathered for a mass in memory of the Polish-born pope.
More than half a million people have "signed" a condolence book in cyberspace.
